<?php

use Krystal\Form\Element;

?>

<style>
    #page-wrapper {
        background: #e0e0e0;
    }
    
    .room-append {
        margin-bottom: 45px;
        border: 1px solid #d8d8d8;
        padding: 26px;
    }
</style>

<div class="container">
    <div class="row">
        <section>
            <div class="wizard">
                <div class="wizard-inner">
                    <div class="connecting-line"></div>
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#step1" data-toggle="tab" aria-controls="step1" role="tab" title="<? $this->show('Step'); ?> 1">
                                <span class="round-tab">
                                    <i class="glyphicon glyphicon-folder-open"></i>
                                </span>
                            </a>
                        </li>

                        <li role="presentation" class="disabled">
                            <a href="#step2" data-toggle="tab" aria-controls="step2" role="tab" title="<? $this->show('Step'); ?> 2">
                                <span class="round-tab">
                                    <i class="glyphicon glyphicon-pencil"></i>
                                </span>
                            </a>
                        </li>

                        <li role="presentation" class="disabled">
                            <a href="#step3" data-toggle="tab" aria-controls="step3" role="tab" title="<? $this->show('Step'); ?> 3">
                                <span class="round-tab">
                                    <i class="glyphicon glyphicon-home"></i>
                                </span>
                            </a>
                        </li>

                        <li role="presentation" class="disabled">
                            <a href="#step4" data-toggle="tab" aria-controls="step4" role="tab" title="<? $this->show('Step'); ?> 4">
                                <span class="round-tab">
                                    <i class="glyphicon glyphicon-picture"></i>
                                </span>
                            </a>
                        </li>

                        <li role="presentation" class="disabled">
                            <a href="#step5" data-toggle="tab" aria-controls="step5" role="tab" title="<? $this->show('Step'); ?> 5">
                                <span class="round-tab">
                                    <i class="glyphicon glyphicon-usd"></i>
                                </span>
                            </a>
                        </li>

                        <li role="presentation" class="disabled">
                            <a href="#complete" data-toggle="tab" aria-controls="complete" role="tab" title="<? $this->show('Complete'); ?>">
                                <span class="round-tab">
                                    <i class="glyphicon glyphicon-ok"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>

                <form role="form" class="form-horizontal" method="POST">
                    <div class="tab-content">
                        <div class="tab-pane active" role="tabpanel" id="step1">
                          <div class="container-fluid">
                              <h3><? $this->show('Step'); ?> 1</h3>

                              <?= Element::hidden(sprintf('translation[%s][id]', $languageId), $hotelId); ?>
                              <?= Element::hidden(sprintf('translation[%s][lang_id]', $languageId), $languageId); ?>
                              <?= Element::hidden('hotel[id]', $hotelId); ?>

                              <div class="row">
                                <div class="col-lg-8">
                                  <fieldset>
                                    <div class="row">
                                        <legend><? $this->show('Please provide basic data of your object'); ?></legend>
                                    </div>

                                    <div class="form-group">
                                      <label><? $this->show('Hotel type'); ?></label>
                                      <?= Element::select('hotel[type_id]', $hotelTypes, null, ['class' => 'form-control']); ?>
                                    </div>

                                    <div class="form-group">
                                      <label><? $this->show('Name'); ?></label>
                                      <?= Element::text(sprintf('translation[%s][name]', $languageId), null, ['class' => 'form-control', 'placeholder' => $this->translate('Type the name of your object')]); ?>
                                    </div>
                                  </fieldset>

                                  <fieldset>
                                    <div class="row">
                                        <legend><? $this->show('Breakfast and restaurant'); ?></legend>
                                    </div>

                                    <div class="form-group">
                                        <label><? $this->show('Do your offer breakfast to your guests?'); ?></label>
                                        <?= Element::select('hotel[breakfast]', $this->translateArray($breakfasts), null, array('class' => 'form-control'), false, function($key, $value){
                                            $map = [
                                                1 => 'breakfast-included',
                                                2 => 'breakfast-extra',
                                                3 => 'breakfast-none'
                                            ];

                                            return [
                                                'data-group' => $map[$key]
                                            ];
                                        }); ?>
                                    </div>

                                    <section data-group="breakfast-extra, breakfast-included">
                                        <div class="form-group">
                                          <label class="col-lg-2 control-label"><? $this->show('Breakfast types'); ?> </label>
                                          <div class="col-lg-10">
                                            <?php foreach ($meals as $meal): ?>
                                            <div class="checkbox">
                                              <label>
                                                <?= Element::checkbox(sprintf('meal[checked][%s]', $meal['id']), (bool) $meal['active'], [], false); ?>
                                                <?= $meal['name']; ?>
                                              </label>
                                            </div>
                                            <?php endforeach; ?>
                                          </div>
                                        </div>
                                    </section>

                                    <section data-group="breakfast-extra">
                                        <h2 class="page-header"><? $this->show('Breakfast price'); ?></h2>

                                        <?php foreach ($globalMealPrices as $globalMealPrice): ?>
                                        <?php $uniq = md5($globalMealPrice['group']); ?>

                                        <div class="form-group">
                                          <label for="<?= $uniq; ?>" class="col-lg-2 control-label"><?= $globalMealPrice['group']; ?> (<?= $globalMealPrice['currency']; ?>)</label>
                                          <div class="col-lg-10">
                                            <?= Element::text(sprintf('meal[price][%s]', $globalMealPrice['price_group_id']), $globalMealPrice['price'], ['id' => $uniq, 'class' => 'form-control']); ?>
                                          </div>
                                        </div>

                                        <?php endforeach; ?>
                                    </section>
                                    
                                    <h2 class="page-header"><? $this->show('Restaurant'); ?></h2>

                                    <div class="form-group">
                                        <label><? $this->show('Do your offer restaurant services to your guests?'); ?></label>
                                        <?= Element::select('hotel[has_restaurant]', $this->translateArray(['0' => 'No', '1' => 'Yes']), null, ['class' => 'form-control'], false, function($key, $value){
                                            $map = [
                                                0 => 'restaurant-none',
                                                1 => 'restaurant-exists'
                                            ];

                                            return [
                                                'data-group' => $map[$key]
                                            ];
                                        }); ?>
                                    </div>

                                    <section data-group="restaurant-exists">
                                        <div class="form-group">
                                          <label class="col-lg-2 control-label"><? $this->show('Opening'); ?></label>
                                          <div class="col-lg-10">
                                            <?= Element::text('hotel[restaurant_opening]', '09:00', ['class' => 'form-control', 'data-plugin' => 'timepicker']); ?>
                                          </div>
                                        </div>

                                        <div class="form-group">
                                          <label class="col-lg-2 control-label"><? $this->show('Closing'); ?></label>
                                          <div class="col-lg-10">
                                            <?= Element::text('hotel[restaurant_closing]', '23:00', ['class' => 'form-control', 'data-plugin' => 'timepicker']); ?>
                                          </div>
                                        </div>
                                    </section>
                                  </fieldset>

                                  <!-- Contact person -->
                                  <fieldset>
                                    <div class="row">
                                        <legend><? $this->show('Contact person'); ?></legend>
                                    </div>

                                    <div class="form-group">
                                        <label><? $this->show('Full name'); ?></label>
                                        <?= Element::text('hotel[contact_full_name]', null, array('class' => 'form-control', 'placeholder' => $this->translate('Type the the full name'))); ?>
                                    </div>

                                    <div class="form-group">
                                        <label><? $this->show('Position'); ?></label>
                                        <?= Element::text('hotel[contact_position]', null, array('class' => 'form-control', 'placeholder' => $this->translate('Type a position'))); ?>
                                    </div>

                                    <div class="form-group">
                                        <label><? $this->show('Email'); ?></label>
                                        <?= Element::text('hotel[contact_email]', null, array('class' => 'form-control', 'placeholder' => $this->translate('Type the email'))); ?>
                                    </div>

                                    <div class="form-group">
                                        <label><? $this->show('First phone'); ?></label>
                                        <?= Element::text('hotel[contact_first_phone]', null, array('class' => 'form-control', 'placeholder' => $this->translate('Type the first phone'))); ?>
                                    </div>

                                    <div class="form-group">
                                        <label><? $this->show('Second phone'); ?></label>
                                        <?= Element::text('hotel[contact_second_phone]', null, array('class' => 'form-control', 'placeholder' => $this->translate('Type the second phone if available'))); ?>
                                    </div>
                                  </fieldset>
                                  <!-- Contact person -->

                                  <!-- Misc -->
                                  <fieldset>
                                    <div class="row">
                                        <legend><? $this->show('Miscellaneous'); ?></legend>
                                    </div>

                                    <div class="form-group">
                                        <?= Element::checkbox('hotel[city_tax_include]', null, ['id' => 'city_tax_include']); ?>
                                        <label for="city_tax_include"><? $this->show('City tax is included in room price by default'); ?></label>
                                    </div>

                                    <div class="form-group">
                                        <label><? $this->show('Online booking'); ?></label>
                                        <?= Element::select('hotel[card_required]', $this->translateArray($cardOptions), 1, ['class' => 'form-control']); ?>
                                    </div>
                                  </fieldset><!-- .Misc -->

                                  <!--Payment time & Arrival -->
                                  <fieldset>
                                    <div class="row">
                                        <legend><? $this->show('Check-in / Check-out'); ?></legend>
                                    </div>

                                    <div class="form-group">
                                        <label><? $this->show('Payment time'); ?></label>
                                        <?= Element::text('hotel[payment_time]', null, array('class' => 'form-control', 'data-plugin' => 'timepicker')); ?>
                                    </div>

                                    <section>
                                        <h2 class="text-muted"><i class="glyphicon glyphicon-resize-small"></i> <? $this->show('Check-in'); ?></h2>

                                        <div class="form-group">
                                            <label><? $this->show('Check-in from'); ?></label>
                                            <?= Element::text('hotel[checkin_from]', null, array('class' => 'form-control', 'data-plugin' => 'timepicker')); ?>
                                        </div>

                                        <div class="form-group">
                                            <label><? $this->show('Check-in to'); ?></label>
                                            <?= Element::text('hotel[checkin_to]', null, array('class' => 'form-control', 'data-plugin' => 'timepicker')); ?>
                                        </div>
                                    </section>

                                    <section>
                                        <h2 class="text-muted"><i class="glyphicon glyphicon-resize-full"></i> <? $this->show('Check-out'); ?></h2>

                                        <div class="form-group">
                                            <label><? $this->show('Check-out from'); ?></label>
                                            <?= Element::text('hotel[checkout_from]', null, array('class' => 'form-control', 'data-plugin' => 'timepicker')); ?>
                                        </div>

                                        <div class="form-group">
                                            <label><? $this->show('Check-out to'); ?></label>
                                            <?= Element::text('hotel[checkout_to]', null, array('class' => 'form-control', 'data-plugin' => 'timepicker')); ?>
                                        </div>
                                    </section>
                                  </fieldset>
                                  <!--Payment time & Arrival -->

                                  <!-- Contacts -->
                                  <fieldset>
                                    <div class="row">
                                        <legend><? $this->show('What are the contact details for your property?'); ?></legend>
                                    </div>

                                    <div class="form-group">
                                      <label><? $this->show('Region'); ?></label>
                                      <?= Element::select('hotel[region_id]', $regions, null, ['data-select' => 'region', 'class' => 'form-control'], false, function($key, $value){
                                            return [
                                                'data-region-id' => $key,
                                            ];
                                      }); ?>
                                    </div>

                                    <div class="form-group">
                                      <label><? $this->show('District'); ?></label>
                                      <select name="hotel[district_id]" class="form-control" data-select="district">
                                        <?php foreach ($districts as $district): ?>
                                        <?= Element::option($district['id'], $district['name'], ['data-region-id' => $district['region_id']]); ?>
                                        <?php endforeach; ?>
                                       </select>
                                    </div>

                                    <div class="form-group">
                                      <label><?= $this->show('Address'); ?></label>
                                      <?= Element::textarea(sprintf('translation[%s][address]', $languageId), null, ['class' => 'form-control', 'placeholder' => $this->translate('Type the full address')]); ?>
                                    </div>

                                    <div class="form-group">
                                      <label><? $this->show('Phone'); ?></label>
                                      <?= Element::text('hotel[phone]', null, ['class' => 'form-control', 'placeholder' => $this->translate('Type the full phone number with code')]); ?>
                                    </div>

                                    <div class="form-group">
                                      <label><? $this->show('ZIP code'); ?></label>
                                      <?= Element::text('hotel[zip]', null, array('class' => 'form-control', 'placeholder' => $this->translate('Type your ZIP code'))); ?>
                                    </div>

                                    <div class="form-group">
                                      <label><? $this->show('Fax'); ?></label>
                                      <?= Element::text('hotel[fax]', null, array('class' => 'form-control', 'placeholder' => $this->translate('Type the fax'))); ?>
                                    </div>

                                    <div class="form-group">
                                      <label><? $this->show('Pick your location on map'); ?></label>
                                      <? $this->loadPartial('map'); ?>
                                    </div>
                                  </fieldset>
                                </div>

                                <? $this->loadPartial('wizard-stick'); ?>
                              </div>

                              <ul class="list-inline pull-right">
                                <li><button type="button" class="btn btn-primary next-step"><? $this->show('Next'); ?></button></li>
                              </ul>
                          </div>
                        </div>

                        <div class="tab-pane" role="tabpanel" id="step2">
                          <h3><? $this->show('Step'); ?> 2</h3>

                          <div class="row">
                              <div class="col-lg-8">
                                  <fieldset>
                                    <div class="row">
                                        <legend><? $this->show('Marketing'); ?></legend>
                                    </div>

                                    <div class="form-group">
                                      <label><?= $this->show('Description'); ?></label>
                                      <?= Element::textarea(sprintf('translation[%s][description]', $languageId), null, ['class' => 'form-control', 'placeholder' => $this->translate('Describe your object. Type what it offers, why people should come to it')]); ?>
                                    </div>

                                    <div class="form-group">
                                      <label><? $this->show('Discount'); ?> %</label>
                                      <?= Element::number('hotel[discount]', null, ['min' => 1, 'max' => 100, 'class' => 'form-control', 'placeholder' => $this->translate('Minimal discount for customers if you provide')]); ?>
                                    </div>

                                    <div class="form-group">
                                      <label><? $this->show('Web-site'); ?></label>
                                      <?= Element::text('hotel[website]', null, ['class' => 'form-control', 'placeholder' => $this->translate('Hotel web-site (if available)')]); ?>
                                    </div>
                                  </fieldset>

                                  <!-- Penalty -->
                                  <fieldset>
                                    <div class="row">
                                        <legend><? $this->show('Penalties for cancellations'); ?></legend>
                                    </div>

                                    <div class="form-group">
                                      <label><? $this->show('Do your refund money on cancellation?'); ?></label>
                                      <?= Element::select('hotel[penality_enabled]', $this->translateArray(['0' => 'No', '1' => 'Yes']), null, ['class' => 'form-control'], false, function($key, $value){
                                            $map = [
                                                0 => 'refund-no',
                                                1 => 'refund-yes'
                                            ];

                                            return [
                                                'data-group' => $map[$key]
                                            ];
                                      }); ?>
                                    </div>

                                    <section data-group="refund-yes">
                                        <div class="form-group">
                                            <label><? $this->show('The penalty is not being withheld when canceling after (hours after making reservation)'); ?></label>
                                            <?= Element::number('hotel[penality_not_taken_after]', null, ['class' => 'form-control', 'min' => 1]); ?>
                                        </div>

                                        <div class="form-group">
                                            <label><? $this->show('But made not later (hours before arrival)'); ?></label>
                                            <?= Element::text('hotel[penality_not_later_arrival]', null, ['class' => 'form-control']); ?>
                                        </div>

                                        <div class="row">
                                            <div class="col-lg-6">
                                                <div class="form-group">
                                                    <label><? $this->show('Before making a cancellation of the reservation'); ?></label>
                                                    <?= Element::text('hotel[penality_cancelation_item]', null, ['class' => 'form-control']); ?>
                                                </div>
                                            </div>

                                            <div class="col-lg-6">
                                                <div class="well">
                                                    <label class="radio-inline">
                                                        <?= Element::radio('hotel[penality_cancelation_type]', 'hr', true); ?> <? $this->show('Hours'); ?>
                                                    </label>

                                                    <label class="radio-inline">
                                                        <?= Element::radio('hotel[penality_cancelation_type]', 'd', false); ?> <? $this->show('Days'); ?>
                                                    </label>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-lg-6">
                                                <div class="form-group">
                                                  <label><? $this->show('A penalty will be withheld'); ?> % </label>
                                                  <?= Element::number('hotel[penality_percentage]', null, ['class' => 'form-control', 'min' => 1, 'max' => 100]); ?>
                                                </div>
                                            </div>

                                            <div class="col-lg-6">
                                                <div class="well">
                                                    <div class="radio">
                                                        <label>
                                                            <?= Element::radio('hotel[penality_percentage_type]', 'T', false); ?> <? $this->show('From total reservation price'); ?>
                                                        </label>
                                                    </div>

                                                    <div class="radio">
                                                        <label>
                                                            <?= Element::radio('hotel[penality_percentage_type]', 'N', true); ?> <? $this->show('From price of the first night'); ?>
                                                        </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    
                                    </section>
                                  </fieldset>
                                  <!-- /Penalty -->
                                  
                                  <fieldset>
                                    <div class="row">
                                        <legend><? $this->show('Сhoice facilites'); ?></legend>
                                    </div>

                                    <? $this->loadPartial('facilities', [
                                        'checklist' => $checklist
                                    ]); ?>
                                  </fieldset>
                              </div>

                              <? $this->loadPartial('wizard-stick'); ?>
                          </div>

                          <ul class="list-inline pull-right">
                            <li><button type="button" class="btn btn-default prev-step"><? $this->show('Previous'); ?></button></li>
                            <li><button type="button" class="btn btn-default next-step"><? $this->show('Skip'); ?></button></li>
                            <li><button type="button" class="btn btn-primary next-step"><? $this->show('Save and continue'); ?></button></li>
                          </ul>
                        </div>

                        <div class="tab-pane" role="tabpanel" id="step3">
                            <h3><?= $this->show('Step'); ?> 3</h3>

                            <fieldset>
                                <h2 class="text-muted"><? $this->show('Add rooms'); ?></h2>

                                <section class="room-append">
                                    <div class="form-group">
                                      <label class="col-lg-2 control-label"><? $this->show('Room type'); ?></label>
                                      <div class="col-lg-10">
                                        <div class="row">
                                            <div class="col-lg-7">
                                                <?= Element::select('room[type][]', $categories, null, ['class' => 'form-control']); ?>
                                            </div>

                                            <div class="col-lg-3">
                                                <?= Element::number('room[qty][]', null, ['class' => 'form-control', 'min' => 1, 'placeholder' => $this->translate('Amount of this type')]); ?>
                                            </div>

                                            <div class="col-lg-2">
                                                <a href="#" class="btn btn-primary"><? $this->show('Add'); ?></a>
                                                <a href="#" class="btn btn-danger hidden"><? $this->show('Remove'); ?></a>
                                            </div>
                                        </div>
                                      </div>
                                    </div>

                                    <div class="form-group">
                                      <label class="col-lg-2 control-label"><? $this->show('Description'); ?></label>
                                      <div class="col-lg-10">
                                        <?= Element::textarea('room[description][]', null, ['class' => 'form-control']); ?>
                                      </div>
                                    </div>

                                    <!-- Capacity -->
                                    <div class="form-group">
                                        <label class="col-lg-2 control-label"><? $this->show('Maximal adults capacity'); ?></label>
                                        <div class="row">
                                            <div class="col-lg-3">
                                                <?= Element::number('room[persons][]', 1, ['class' => 'form-control', 'min' => 1, 'max' => 30]); ?>
                                            </div>

                                            <div class="col-lg-5">
                                                <label class="col-lg-5 control-label"><?php $this->show('Children capacity'); ?></label>
                                                <div class="col-lg-7">
                                                    <?= Element::select('room[children][]', $this->translateArray($children), null, ['class' => 'form-control']); ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- /Capacity -->

                                    <?php foreach ($priceGroups as $priceGroup): ?>
                                    <div class="form-group">
                                      <label class="col-lg-2 control-label"><strong><? $this->show('Price'); ?> (<?= $priceGroup['currency']; ?>)</strong> <?= $priceGroup['name']; ?></label>
                                      <div class="col-lg-10">
                                        <?= Element::number(sprintf('room[price_group_ids][%s][]', $priceGroup['id']), isset($priceGroup['price']) ? $priceGroup['price'] : null, array('class' => 'form-control')); ?>
                                      </div>
                                    </div>
                                    <?php endforeach; ?>

                                </section>
                            </fieldset>

                            <ul class="list-inline pull-right">
                                <li><button type="button" class="btn btn-default prev-step"><? $this->show('Previous'); ?></button></li>
                                <li><button type="button" class="btn btn-primary next-step"><? $this->show('Save and continue'); ?></button></li>
                            </ul>
                        </div>

                        <div class="tab-pane" role="tabpanel" id="step4">
                            <h3><? $this->show('Step'); ?> 4</h3>
                            <div class="alert alert-dismissible alert-info">
                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                <p>
                                    <?= $this->translate('Keep in mind! The size of each photo must not be greater than - %s', '700KB'); ?>
                                    <br /> 
                                    <?= $this->translate('Recommended size for photos - %s', '850x450'); ?>
                                </p>
                            </div>

                            <p><? $this->show('Upload photos'); ?></p>

                            <p><a href="#" class="btn btn-primary" data-button="file-add"><? $this->show('Add a photo'); ?></a></p>

                            <section class="image-wrapper">
                                <div class="fileinput fileinput-new hidden" data-provides="fileinput">
                                  <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;"></div>
                                  <div>
                                    <span class="btn btn-default btn-file">
                                        <span class="fileinput-new"><? $this->show('Select image'); ?></span>
                                        <span class="fileinput-exists"><? $this->show('Change'); ?></span>
                                        <input type="file" name="files[]" accept="image/*" />
                                    </span>

                                    <a href="#" class="btn btn-default fileinput-exists" data-button="fileinput-remove" data-dismiss="fileinput"><? $this->show('Remove'); ?></a>
                                  </div>
                                </div>
                            </section>

                            <ul class="list-inline pull-right">
                                <li><button type="button" class="btn btn-default prev-step"><? $this->show('Previous'); ?></button></li>
                                <li><button type="button" class="btn btn-default next-step"><? $this->show('Skip'); ?></button></li>
                                <li><button type="button" class="btn btn-primary btn-info-full next-step"><? $this->show('Save and continue'); ?></button></li>
                            </ul>
                        </div>

                        <div class="tab-pane" role="tabpanel" id="step5">
                            <h3><? $this->show('Step'); ?> 5</h3>

                            <div class="row">
                                <div class="col-lg-8">
                                    <fieldset>
                                        <div class="row">
                                            <legend><? $this->show('Please enter your payment gateway data'); ?></legend>
                                        </div>

                                        <?php foreach ($payments as $system => $gateways): ?>
                                        <h3 class="page-header"><i class="glyphicon glyphicon-credit-card"></i> <?= $system; ?></h3>

                                        <fieldset>
                                        <?php foreach ($gateways as $index => $gateway): ?>
                                        <?php $uniq = sprintf('field-%s', $index); ?>
                                        <div class="form-group">
                                          <label for="<?= $uniq; ?>"><?= $gateway['field']; ?></label>
                                          <?= Element::text(sprintf('payment[%s]', $gateway['field_id']), $gateway['value'], ['class' => 'form-control', 'id' => $uniq]); ?>
                                        </div>
                                        <?php endforeach; ?>
                                        </fieldset>

                                        <?php endforeach; ?>
                                    </fieldset>
                                </div>

                                <? $this->loadPartial('wizard-stick'); ?>
                            </div>
                            
                            <ul class="list-inline pull-right">
                                <li><button type="button" class="btn btn-default prev-step"><? $this->show('Previous'); ?></button></li>
                                <li><button type="button" class="btn btn-default next-step"><? $this->show('Skip'); ?></button></li>
                                <li><button type="button" class="btn btn-primary btn-info-full next-step"><? $this->show('Save and continue'); ?></button></li>
                            </ul>
                        </div>

                        <div class="tab-pane" role="tabpanel" id="complete">
                            <h3><? $this->show('Thank you!'); ?></h3>
                            <p><? $this->show('You have successfully completed all steps'); ?></p>
                            <p><? $this->show('Remained steps'); ?>:</p>

                            <ul>
                                <li><? $this->show('Configure room types and their corresponding prices'); ?></li>
                                <li><? $this->show('Configure architecture'); ?></li>
                            </ul>

                            <ul class="list-inline pull-right">
                                <li><button type="submit" class="btn btn-success btn-info-full next-step"><? $this->show('Configure room types'); ?></button></li>
                            </ul>
                        </div>

                        <div class="clearfix"></div>
                    </div>
                </form>
            </div>
        </section>
    </div>
</div>
