<!DOCTYPE html>
<html lang="<?= $locale; ?>">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="csrf-token" content="<?php echo $csrfToken; ?>" />
    <title><?= $appName; ?></title>
    
    <?php foreach ($this->getPluginBag()->getStylesheets() as $path): ?>
    <link href="<?php echo $path; ?>" rel="stylesheet" />
    <?php endforeach; ?>
  </head>
  <body role="document">
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<?= $this->url('Site:Crm@indexAction'); ?>"><?= $appName; ?></a>
        </div>
        
        <div id="navbar" class="collapse navbar-collapse">
          <?php if ($isLoggedIn): ?>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><? $this->show('Reservation'); ?> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="<?= $this->url('Site:Reservation@tableAction'); ?>"><?php $this->show('Desktop'); ?></a></li>
                <li><a href="<?= $this->url('Site:Reservation@indexAction', null); ?>"><?php $this->show('Current guests'); ?></a></li>
                <li class="dropdown-header"><? $this->show('Management'); ?></li>
                <li><a href="<?= $this->url('Site:Reservation@addAction', null); ?>"><?php $this->show('New reservation'); ?></a></li>
                <li><a href="<?= $this->url('Site:Reservation@findAction'); ?>"><?php $this->show('Find a free room'); ?></a></li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><? $this->show('My hotel'); ?> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="<?= $this->url('Site:Architecture:Grid@indexAction'); ?>"><? $this->show('Architecture'); ?></a></li>
                <li><a href="<?= $this->url('Site:Architecture:RoomType@indexAction'); ?>"><? $this->show('Room types'); ?></a></li>
                <li><a href="<?= $this->url('Site:Inventory@indexAction'); ?>"><? $this->show('Inventory'); ?></a></li>
                <li><a href="<?= $this->url('Site:Service@indexAction'); ?>"><? $this->show('Services'); ?></a></li>
                <li><a href="<?= $this->url('Site:Architecture:RoomCleaning@indexAction'); ?>"><? $this->show('Room cleaning'); ?></a></li>
                <li><a href="<?= $this->url('Site:Hotel@indexAction'); ?>"><? $this->show('Hotel information'); ?></a></li>
                <li><a href="<?= $this->url('Site:Facility:Grid@indexAction'); ?>"><? $this->show('Facilities'); ?></a></li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><? $this->show('Reports'); ?> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="<?= $this->createQueryUrl('Site:Reservation@indexAction', array('leaving' => 'today')); ?>"><? $this->show('List of departures today'); ?></a></li>
                <li><a href="<?= $this->createQueryUrl('Site:Reservation@indexAction', array('leaving' => 'tomorrow')); ?>"><? $this->show('Going out tomorrow'); ?></a></li>
                <li><a href="<?= $this->createQueryUrl('Site:Reservation@indexAction', array('coming' => 'today')); ?>"><? $this->show('List of coming today'); ?></a></li>
                <li><a href="<?= $this->createQueryUrl('Site:Reservation@indexAction', array('coming' => 'tomorrow')); ?>"><? $this->show('List of coming tomorrow'); ?></a></li>
                <li><a href="<?= $this->url('Site:Transaction@indexAction', null); ?>"><? $this->show('Transactions'); ?></a></li>
              </ul>
            </li>
          </ul>
          
          <ul class="nav navbar-nav navbar-right">
            <li><a href="<?= $this->url('Site:Auth@logoutAction'); ?>"><?php $this->show('Logout'); ?></a></li>
          </ul>
          <?php endif; ?>
        </div>
      </div>
    </nav>
    
    <div class="container" role="main">
        <?php if ($flashBag->has('danger')): ?>
        <div class="alert alert-danger" role="alert"><i class="glyphicon glyphicon-ok"></i> <?php $this->show($flashBag->get('danger')); ?></div>
        <?php endif; ?>

        <?php if ($flashBag->has('success')): ?>
        <div class="alert alert-success" role="alert"><i class="glyphicon glyphicon-ok"></i> <?php $this->show($flashBag->get('success')); ?></div>
        <?php endif; ?>

        <?php if ($flashBag->has('warning')): ?>
        <div class="alert alert-warning" role="alert"><i class="glyphicon glyphicon-ok"></i> <?php $this->show($flashBag->get('warning')); ?></div>
        <?php endif; ?>

        <?php $this->loadPartial('breadcrumbs'); ?>

        <?php echo $fragment; ?>
    </div>
    
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <div class="modal fade" id="errors-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title"><?php $this->show('Warning'); ?></h4>
            </div>

            <div class="modal-body"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal"><?php $this->show('OK'); ?></button>
            </div>
         </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->  
    </div>

    <?php foreach ($this->getPluginBag()->getScripts() as $script): ?>
    <script src="<?php echo $script; ?>"></script>
    <?php endforeach;?>
  </body>
</html>