<?php

use Krystal\Date\TimeHelper;
use Site\Service\UserService;

?>

<!DOCTYPE html>
<html lang="<?= $locale; ?>">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="csrf-token" content="<?php echo $csrfToken; ?>" />
    <title><?= $appName; ?></title>
    
    <?php foreach ($this->getPluginBag()->getStylesheets() as $path): ?>
    <link href="<?php echo $path; ?>" rel="stylesheet" />
    <?php endforeach; ?>
  </head>
  <body role="document">
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<?= $this->url($role == UserService::USER_ROLE_ADMIN ? 'Site:Property@indexAction' : 'Site:Crm@indexAction', null); ?>"><?= $appName; ?></a>
        </div>
        
        <div id="navbar" class="collapse navbar-collapse">
          <?php if ($isLoggedIn): ?>
          <ul class="nav navbar-nav">

            <?php if ($role == UserService::USER_ROLE_USER || $admin == true): ?>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><? $this->show('Reservation'); ?> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="<?= $this->url('Site:Reservation@tableAction', null); ?>"><i class="glyphicon glyphicon-blackboard"></i> <?php $this->show('Desktop'); ?></a></li>
                <li><a href="<?= $this->url('Site:Reservation@indexAction', null); ?>"><i class="glyphicon glyphicon-user"></i> <?php $this->show('Clients'); ?></a></li>
                <li class="dropdown-header"><? $this->show('Management'); ?></li>
                <li><a href="<?= $this->url('Site:Reservation@addAction', null); ?>"><i class="glyphicon glyphicon-pencil"></i> <?php $this->show('New reservation'); ?></a></li>
                <li><a href="<?= $this->url('Site:Reservation@findAction'); ?>"><i class="glyphicon glyphicon-search"></i> <?php $this->show('Find a free room'); ?></a></li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><? $this->show('My hotel'); ?> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="<?= $this->url('Site:Hotel@indexAction'); ?>"><i class="glyphicon glyphicon-list-alt"></i> <? $this->show('Hotel information'); ?></a></li>
                <li><a href="<?= $this->url('Site:Architecture:RoomCleaning@indexAction'); ?>"><i class="glyphicon glyphicon-refresh"></i> <? $this->show('Room cleaning'); ?></a></li>
                <li><a href="<?= $this->url('Site:Review:Review@indexAction'); ?>"><i class="glyphicon glyphicon-signal"></i> <? $this->show('Customer reviews'); ?></a></li>
                <li class="dropdown-header"><? $this->show('Helpers'); ?></li>
                <li><a href="<?= $this->url('Site:Architecture:RoomType@indexAction'); ?>"><i class="glyphicon glyphicon-link"></i> <? $this->show('Room types'); ?></a></li>
                <li><a href="<?= $this->url('Site:Architecture:Grid@indexAction'); ?>"><i class="glyphicon glyphicon-home"></i> <? $this->show('Architecture'); ?></a></li>
                <li><a href="<?= $this->url('Site:Service@indexAction'); ?>"><i class="glyphicon glyphicon-tags"></i> <? $this->show('Services'); ?></a></li>
                <li><a href="<?= $this->url('Site:Discount@indexAction'); ?>"><i class="glyphicon glyphicon-retweet"></i> <? $this->show('Discounts'); ?></a></li>
                <li><a href="<?= $this->url('Site:Inventory@indexAction'); ?>"><i class="glyphicon glyphicon-resize-full"></i> <? $this->show('Inventory'); ?></a></li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><? $this->show('Reports'); ?> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="<?= $this->url('Site:Transaction@indexAction', null); ?>"><i class="glyphicon glyphicon-credit-card"></i> <? $this->show('Transactions'); ?></a></li>
                <li><a href="<?= $this->url('Site:Stat@indexAction'); ?>"><i class="glyphicon glyphicon-stats"></i> <? $this->show('Statistic'); ?></a></li>
              </ul>
            </li>
            <?php endif; ?>

            <?php if ($role == UserService::USER_ROLE_ADMIN || $admin == true): ?>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><? $this->show('Administration'); ?> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="<?= $this->url('Site:Property@indexAction', null); ?>"><? $this->show('Properties'); ?></a></li>
                <li><a href="<?= $this->url('Site:Review:ReviewType@indexAction'); ?>"><? $this->show('Review types'); ?></a></li>
                <li><a href="<?= $this->url('Site:Region@indexAction'); ?>"><? $this->show('Regions'); ?></a></li>
                <li><a href="<?= $this->url('Site:PaymentSystem@indexAction'); ?>"><i class="glyphicon glyphicon-card"></i> <? $this->show('Payment systems'); ?></a></li>
                <li><a href="<?= $this->url('Site:Facility:Grid@indexAction'); ?>"><i class="glyphicon glyphicon-check"></i> <? $this->show('Facilities'); ?></a></li>
                <li><a href="<?= $this->url('Site:Language@indexAction'); ?>"><i class="glyphicon glyphicon-flag"></i> <? $this->show('Languages'); ?></a></li>
                <li><a href="<?= $this->url('Site:PriceGroup@indexAction'); ?>"><i class="glyphicon glyphicon-euro"></i> <? $this->show('Price groups'); ?></a></li>
              </ul>
            </li>

            <?php endif; ?>
          </ul>
          
          <ul class="nav navbar-nav navbar-right">
            <li><a><span class="date"></span></a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><? $this->show('Language'); ?> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <?php foreach ($languages as $language): ?>
                <li>
                    <a href="<?= $this->url('Site:Language@switchAction', $language['code']); ?>">
                        <?php if ($code == $language['code']): ?>
                        <i class="glyphicon glyphicon-ok"></i>
                        <?php endif; ?>
                        <?= $language['name']; ?>
                    </a>
                </li>
                <?php endforeach; ?>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="glyphicon glyphicon-user"></i> <?= $name; ?> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="<?= $this->url('Site:Settings@changePasswordAction'); ?>"><i class="glyphicon glyphicon-flash"></i> <?php $this->show('Change password'); ?></a></li>
                <li><a href="<?= $this->url('Site:Auth@logoutAction'); ?>"><i class="glyphicon glyphicon-log-out"></i> <?php $this->show('Logout'); ?></a></li>
              </ul>
            </li>
          </ul>
          <?php endif; ?>
        </div>
      </div>
    </nav>

    <div class="container" role="main">
        <?php if ($flashBag->has('danger')): ?>
        <div class="alert alert-danger" role="alert">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <i class="glyphicon glyphicon-ok"></i> <?php $this->show($flashBag->get('danger')); ?>
        </div>
        <?php endif; ?>

        <?php if ($flashBag->has('success')): ?>
        <div class="alert alert-success" role="alert">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <i class="glyphicon glyphicon-ok"></i> <?php $this->show($flashBag->get('success')); ?>
        </div>
        <?php endif; ?>

        <?php if ($flashBag->has('warning')): ?>
        <div class="alert alert-warning" role="alert">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <i class="glyphicon glyphicon-ok"></i> <?php $this->show($flashBag->get('warning')); ?>
        </div>
        <?php endif; ?>

        <?php $this->loadPartial('breadcrumbs'); ?>
        <?php echo $fragment; ?>
    </div>
    
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <footer class="hidden-print">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <p>Copyrights <?= date('Y'); ?> NGS Labs</p>
                </div>

                <div class="col-lg-6 pull-right">
                    <ul class="pull-right">
                        <li><a href="#"><? $this->show('FAQ'); ?></a></li>
                        <li><a href="#"><? $this->show('Terms & Conditions'); ?></a></li>
                        <li><a href="<?= $this->url('Site:Feedback@indexAction'); ?>"><? $this->show('Help & Support'); ?></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <div class="modal fade" id="errors-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title"><?php $this->show('Response'); ?></h4>
            </div>

            <div class="modal-body"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal"><?php $this->show('OK'); ?></button>
            </div>
         </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->  
    </div>

    <!-- Modal -->
    <div id="removeConfirmationModal" class="modal fade" role="dialog">
      <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title"><? $this->show('Confirm'); ?></h4>
          </div>

          <div class="modal-body">
            <p><? $this->show('Are you sure you want to remove this element permamently?'); ?></p>
          </div>

          <div class="modal-footer">
            <a class="btn btn-danger" href="#" data-button="confirm-removal"><? $this->show('Yes'); ?></a>
            <a class="btn btn-default" data-dismiss="modal"><? $this->show('No'); ?></a>
          </div>
        </div>
      </div>
    </div>
    
    <?php foreach ($this->getPluginBag()->getScripts() as $script): ?>
    <script src="<?php echo $script; ?>"></script>
    <?php endforeach;?>

    <?php if (isset($stat)): ?>
    <?php $months = json_encode($this->translateArray(array_values(TimeHelper::getMonths()))); ?>

    <script>
        var MONTHS = <?= $months; ?>;
        var config = {
            type: 'line',
            data: {
                labels: MONTHS,
                datasets: [{
                    label: "<? $this->show('Total reservations'); ?>",
                    borderColor: window.chartColors.red,
                    backgroundColor: window.chartColors.red,
                    data: [
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor()
                    ],
                }, {
                    label: "<? $this->show('Total incoming'); ?>",
                    borderColor: window.chartColors.blue,
                    backgroundColor: window.chartColors.blue,
                    data: [
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor()
                    ],
                },  {
                    label: "<? $this->show('Total tax'); ?>",
                    borderColor: window.chartColors.yellow,
                    backgroundColor: window.chartColors.yellow,
                    data: [
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor(),
                        randomScalingFactor()
                    ],
                }]
            },
            options: {
                responsive: true,
                title:{
                    display:true,
                    text:"<? $this->show('Summary statistic for year'); ?>"
                },
                tooltips: {
                    mode: 'index',
                },
                hover: {
                    mode: 'index'
                }
            }
        };

        window.onload = function() {
            var ctx = document.getElementById("canvas").getContext("2d");
            window.myLine = new Chart(ctx, config);
        };

    </script>
    <?php endif; ?>
  </body>
</html>