<?php

use Site\Service\UserService;

?>

<script>

window.priceGroupStat = {
    title: "<?php $this->show('Reservations by price groups'); ?>",
    reservations: <?= json_encode(array_column($priceGroupReservations, 'reservations')); ?>,
    groups: <?= json_encode(array_column($priceGroupReservations, 'currency')); ?>
};

</script>

<?php if (!$active && $isLoggedIn && $role != UserService::USER_ROLE_ADMIN): ?>
<div class="alert alert-dismissible alert-danger">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong><? $this->show('Warning'); ?>!</strong> <? $this->show('Your hotel is not visible on the site. Please ask administration to enable it'); ?>
</div>
<?php endif; ?>

<div class="row">
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-universal-access fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><?= $states[0]; ?></div>
                        <div><? $this->show('New reservations'); ?></div>
                    </div>
                </div>
            </div>

            <a href="<?= $this->createQueryUrl('Site:Reservation@indexAction', ['filter[state]' => '0']); ?>">
                <div class="panel-footer">
                    <span class="pull-left"><? $this->show('View'); ?></span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>

    <div class="col-lg-3 col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="glyphicon glyphicon-ok fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><?= $states[1]; ?></div>
                        <div><? $this->show('Confirmed'); ?></div>
                    </div>
                </div>
            </div>

            <a href="<?= $this->createQueryUrl('Site:Reservation@indexAction', ['filter[state]' => '1']); ?>">
                <div class="panel-footer">
                    <span class="pull-left"><? $this->show('View'); ?></span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>

    <div class="col-lg-3 col-md-6">
        <div class="panel panel-yellow">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-question-circle-o fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><?= $states[2]; ?></div>
                        <div><? $this->show('Unconfirmed'); ?></div>
                    </div>
                </div>
            </div>

            <a href="<?= $this->createQueryUrl('Site:Reservation@indexAction', ['filter[state]' => '2']); ?>">
                <div class="panel-footer">
                    <span class="pull-left"><? $this->show('View'); ?></span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>

    <div class="col-lg-3 col-md-6">
        <div class="panel panel-red">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="glyphicon glyphicon-remove fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><?= $states[3]; ?></div>
                        <div><? $this->show('Cancellations'); ?></div>
                    </div>
                </div>
            </div>

            <a href="<?= $this->createQueryUrl('Site:Reservation@indexAction', ['filter[state]' => '3']); ?>">
                <div class="panel-footer">
                    <span class="pull-left"><? $this->show('View'); ?></span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-long-arrow-right fa-fw"></i> <? $this->show('Sales funnel'); ?></h3>
            </div>

            <div class="panel-body">
                <canvas id="chart-area"></canvas>
            </div>
        </div>
    </div>

    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-clock-o fa-fw"></i> <? $this->show('Recent actions'); ?></h3>
            </div>

            <div class="panel-body">
                <div class="list-group">
                    <?php foreach ($reservations as $reservation): ?>
                    <a href="<?= $this->url('Site:Reservation@printAction', $reservation['id']); ?>" class="list-group-item">
                        <i class="fa fa-fw fa-user"></i> <?= $reservation['full_name']; ?> <? $this->show('has been registered'); ?>
                    </a>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-money fa-fw"></i> <? $this->show('Recent transactions'); ?></h3>
            </div>

            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th><? $this->show('Date'); ?></th>
                                <th><? $this->show('Amount'); ?></th>
                            </tr>
                        </thead>

                        <tbody>
                            <?php foreach ($transactions as $transaction): ?>
                            <tr>
                                <td><?= $transaction['id']; ?></td>
                                <td><?= $transaction['datetime']; ?></td>
                                <td><?= number_format($transaction['amount']), ' ', $transaction['currency']; ?></td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>

                <div class="text-right">
                    <a href="<?= $this->url('Site:Transaction@indexAction', null); ?>"><? $this->show('Show all transactions'); ?> <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
