<?php

use Krystal\Form\Element;

?>

<div class="background-wrapper">
    <form class="form-horizontal" autocomplete="off">
      <p><img src="/data/uploads/logo.png" /></p>
      <br />

      <fieldset>
        <div class="form-group">
            <?= Element::text('login', null, ['class' => 'form-control input-lg', 'placeholder' => $this->translate('Your login')]); ?>
        </div>
        
        <div class="form-group">
            <?= Element::password('password', null, ['class' => 'form-control input-lg', 'placeholder' => $this->translate('Password')]); ?>
            <div class="checkbox">
              <label>
                <?= Element::checkbox('remember', false); ?>
                <?php $this->show('Remember me'); ?>
              </label>
            </div>
        </div>
        
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-lg"><?php $this->show('Login'); ?></button>
        </div>
      </fieldset>
    </form>
</div>