<?php

use Krystal\Form\Element;

?>

<h2 class="page-header"><i class="glyphicon glyphicon-list-alt"></i> <? $this->show('Payment fields for'); ?> <?= $name; ?> <small>(<?= count($fields); ?>)</small></h2>

<div class="row">
    <div class="col-lg-6">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th><?php $this->show('Name'); ?></th>
                    <th><?php $this->show('Order'); ?></th>
                    <th><?php $this->show('Actions'); ?></th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($fields as $index => $field): ?>
                <tr class="<?= $field['id'] == $entity['id'] ? 'success' : null; ?>">
                    <td><?= $index + 1; ?></td>
                    <td><?= $field['name']; ?></td>
                    <td><?= $field['order']; ?></td>
                    <td>
                        <a href="<?= $this->url('Site:PaymentField@editAction', $field['id']); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                        <a data-button="delete" href="<?= $this->url('Site:PaymentField@deleteAction', $field['id']); ?>"><i class="glyphicon glyphicon-remove"></i></a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <div class="col-lg-6">
        <form class="form-horizontal" action="<?= $this->url('Site:PaymentField@saveAction'); ?>">
          <fieldset>
            <legend><i class="glyphicon glyphicon-pencil"></i> <?php $this->show(!$entity['id'] ? 'Add new field' : 'Edit the field'); ?></legend>

            <?= Element::hidden('id', $entity['id']); ?>
            <?= Element::hidden('payment_system_id', $entity['payment_system_id']); ?>

            <div class="form-group">
              <label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
              <div class="col-lg-10">
                <?= Element::text('name', $entity['name'], array('class' => 'form-control')); ?>
              </div>
            </div>

            <div class="form-group">
              <label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
              <div class="col-lg-10">
                <?= Element::number('order', $entity['order'], array('class' => 'form-control', 'min' => '')); ?>
              </div>
            </div>

            <div class="form-group">
              <div class="col-lg-10 col-lg-offset-2">
                <button type="submit" class="btn btn-primary"><?php $this->show('Submit'); ?></button>

                <?php if ($entity['id']): ?>
                <a href="<?= $this->url('Site:PaymentField@indexAction', $entity['payment_system_id']); ?>" class="btn btn-danger"><?php $this->show('Cancel'); ?></a>
                <?php endif; ?>

              </div>
            </div>
          </fieldset>
        </form>
    </div>
</div>
