<?php

use Krystal\Form\Element;
use Site\Service\ReservationService;

?>

<div>
    <form class="form-horizontal" action="<?= $this->url('Site:Reservation@chessAction', null); ?>">
      <fieldset>
        <legend><i class="glyphicon glyphicon-search"></i> <? $this->show('Filter'); ?></legend>
        <div class="form-group">
          <label for="select" class="col-lg-2 control-label"><? $this->show('Period'); ?></label>
          <div class="col-lg-10">
            <?= Element::select('period', $this->translateArray($periods), $period, ['class' => 'form-control']); ?>
          </div>
        </div>

        <div class="form-group">
          <label for="select" class="col-lg-2 control-label"><? $this->show('Type'); ?></label>
          <div class="col-lg-10">
            <?= Element::select('type', $types, $type, ['class' => 'form-control'], $this->translate('All')); ?>
          </div>
        </div>

        <div class="form-group">
          <div class="col-lg-10 col-lg-offset-2">
            <button type="submit" onclick="this.form.submit()" class="btn btn-primary"><? $this->show('Apply'); ?></button>
          </div>
        </div>
      </fieldset>
    </form>
</div>

<div class="row chess-grid-row">
    <div class="col-lg-2">
        <table class="table chess-grid">
            <thead>
                <tr>
                    <td><? $this->show('Room'); ?></td>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($rooms as $room): ?>
                <tr>
                    <td>
                        <span class="room-name">
                            <?php echo $room['name']; ?>
                            <small><?php echo $room['type']; ?></small>
                        </span>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <div class="col-lg-10">
        <div class="table-responsive">
            <table class="table chess-grid">
                <thead>
                    <tr>
                        <?php foreach ($dates as $index => $date): ?>
                        <td class="text-center <?php echo $index == 0 ? 'chess-grid-col-today' : null; ?>">
                            <?php $this->show($date['weekday']); ?>
                            <br />
                            <?php echo $date['date']; ?>
                        </td>
                        <?php endforeach; ?>
                    </tr>
                </thead>

                <tbody>
                    <?php foreach ($rooms as $room): ?>
                    <tr>
                        <?php foreach ($dates as $date): ?>
                        <?php
                            $title = sprintf('%s - %s', $this->translate($date['weekday']), $date['date']);
                        ?>
                        <td>
                            <?php if (ReservationService::isDateInRange($date['date'], $room['arrival'], $room['departure'])): ?>
                            
                            <span data-toggle="tooltip" title="<?php echo $title; ?>" class="room-taken">
                                <a href="#"></a>
                            </span>
                            <?php else: ?>
                            <span data-toggle="tooltip" title="<?php echo $title; ?>"class="room-free">
                                <a href="<?= $this->createQueryUrl('Site:Reservation@addAction', array('room_id' => $room['id'], 'arrival' => $date['date'])); ?>"></a> 
                            </span>
                            <?php endif; ?>
                        </td>
                        <?php endforeach; ?>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

