<?php

use Krystal\Form\Element;

?>

<?php if (empty($rooms)): ?>
<p class="text-center">
    <span class="text-danger"><?= $this->show('Error'); ?></span>: <? $this->show('In order to do reservations, you must create at least one room!'); ?>
</p>

<?php else: ?>

<form class="form-horizontal" action="<?= $this->url('Site:Reservation@saveAction'); ?>">
    <?php $this->loadPartial('reservation-form'); ?>
</form>

<?php endif; ?>