<?php

use Krystal\Grid\Grid;
use Krystal\Form\Element;
use Krystal\Iso\ISO3166\Country;

?>

<form action="<?= $route; ?>">

    <div class="row">
        <div class="col-lg-6">
            <div class="summary">
                <h4 class="page-header"><i class="glyphicon glyphicon-user"></i> <?php $this->show($title); ?> 
                    <?php if ($paginator->getSummary() != 0): ?>
                    <small> (<?php $this->show('Displayed'); ?> <?= $paginator->getSummary(); ?> <?php $this->show('of'); ?> <?= $paginator->getTotalAmount(); ?>) </small>
                    <?php endif; ?>
                </h4>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <button class="btn btn-primary" type="submit" onclick="this.form.submit()"><i class="glyphicon glyphicon-search"></i> <? $this->show('Filter'); ?></button>
                    <?php if ($hasFilter): ?>
                    <a class="btn btn-danger" href="<?= $this->url('Site:Reservation@indexAction'); ?>"><i class="glyphicon glyphicon-file"></i> <? $this->show('Reset filter'); ?></a>
                    <?php endif; ?>
                </div>

                <div class="col-lg-12">
                    <br />

                    <a href="<?= $this->createQueryUrl('Site:Reservation@indexAction', array('leaving' => 'today')); ?>"><span class="label label-default"><? $this->show('List of departures today'); ?></span></a>
                    <a href="<?= $this->createQueryUrl('Site:Reservation@indexAction', array('leaving' => 'tomorrow')); ?>"><span class="label label-success"><? $this->show('Going out tomorrow'); ?></span></a>
                    <a href="<?= $this->createQueryUrl('Site:Reservation@indexAction', array('coming' => 'today')); ?>"><span class="label label-primary"><? $this->show('List of coming today'); ?></span></a>
                    <a href="<?= $this->createQueryUrl('Site:Reservation@indexAction', array('coming' => 'tomorrow')); ?>"><span class="label label-info"><? $this->show('List of coming tomorrow'); ?></span></a>
                </div>
            </div>
        </div>

        <div class="col-lg-6 <?= $hideRange === true ? 'hidden' : null; ?>">
            <div class="pull-right">
                <h3><i class="glyphicon glyphicon-time"></i> <? $this->show('Range filter'); ?></h3>

                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                          <?= Element::text('from', $from, array('class' => 'form-control', 'data-plugin' => 'datetimepicker', 'placeholder' => $this->translate('From'))); ?>

                          <br />

                          <div class="form-inline">
                            <div class="controls-row">
                              <label class="radio inline">
                                <?= Element::radio('type', 'arrival', isset($query['type']) && $query['type'] == 'arrival'); ?> <? $this->show('Arrival'); ?>
                              </label>
                              <label class="radio inline">
                                <?= Element::radio('type', 'departure', isset($query['type']) && $query['type'] === 'departure'); ?> <? $this->show('Departure'); ?>
                              </label>
                            </div>
                          </div>
                        </div>
                    </div>

                    <div class="col-lg-6">
                        <div class="form-group">
                            <?= Element::text('to', $to, array('class' => 'form-control', 'data-plugin' => 'datetimepicker', 'placeholder' => $this->translate('To'))); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <br />

    <div class="table-responsive">
        <?= Grid::render($data, [
            // A column to be considered as a primary key
            'pk' => 'id',
            'batch' => false,
            'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
            'columns' => [
                [
                    'column' => 'id',
                    'label' => 'ID'
                ],

                [
                    'column' => 'country',
                    'type' => 'select',
                    'filter' => $countries,
                    'value' => function($row){
                        $country = new Country();
                        return $country->getCountryByCode($row['country']);
                    }
                ],

                [
                    'column' => 'full_name',
                    'type' => 'text',
                    'filter' => true
                ],

                [
                    'column' => 'room_id',
                    'type' => 'select',
                    'filter' => $rooms,
                    'label' => 'Room',
                    'hidden' => !$showRooms,
                    'value' => function($row){
                        return $row['room'];
                    }
                ],

                [
                    'column' => 'state',
                    'type' => 'select',
                    'filter' => $this->translator->translateArray($reservationCollection->getAll()),
                    'label' => 'Reservation state',
                    'translateable' => true,
                    'value' => function($row) use ($reservationCollection){
                        return $reservationCollection->findByKey($row['state']);
                    }
                ],

                [
                    'column' => 'arrival',
                    'type' => 'date',
                    'filter' => true
                ],

                [
                    'column' => 'departure',
                    'type' => 'date',
                    'filter' => true
                ]
            ],

            'actions' => [
                'view' => function($row){
                    return Element::link('<i class="glyphicon glyphicon-search"></i>', $this->url('Site:Reservation@viewAction', $row['id']), ['data-button' => 'view']);
                },
                'print' => function($row){
                    return Element::link('<i class="glyphicon glyphicon-tags"></i>', $this->url('Site:Reservation@printAction', $row['id']));
                },
                'update' => function($row){
                    return Element::link('<i class="glyphicon glyphicon-pencil"></i>', $this->url('Site:Reservation@editAction', $row['id']));
                },
                'delete' => function($row){
                    return Element::link('<i class="glyphicon glyphicon-remove"></i>', $this->url('Site:Reservation@deleteAction', $row['id']));
                }
            ]

        ], $this->translator, $route, $query); ?>

    </div>

    <? $this->loadPartial('pagination'); ?>

</form>

<? $this->loadPartial('client-modal'); ?>
