<?php

use Krystal\Iso\ISO3166\Country;
use Site\Collection\LegalStatusCollection;
use Site\Collection\PurposeCollection;
use Site\Collection\PaymentTypeCollection;
use Site\Collection\ReservationCollection;
use Site\Collection\StatusCollection;
use Krystal\Grid\ListView;

?>

<p>
    <a href="#" data-button="back" class="btn btn-info hidden-print"><i class="glyphicon glyphicon-chevron-left"></i> <?php $this->show('Back'); ?></a>
    <a href="#" data-button="print" class="btn btn-success hidden-print"><i class="glyphicon glyphicon-print"></i> <?php $this->show('Print this page'); ?></a>
</p>

<h2><?php $this->show('Invoice'); ?> №<?= $entity['id']; ?></h2>

<div class="row">
    <div class="col-lg-6">
        <?= (new ListView($entity, [
            'columns' => [
                ['column' => 'id', 'title' => 'ID'],
                ['column' => 'full_name'],
                ['column' => 'passport'],
                [
                    'column' => 'gender', 
                    'translate' => true,
                    'value' => function($column, $value){
                        return str_replace(array('M', 'F'), array('Male', 'Female'), $value);
                    }
                ],
                [
                    'column' => 'country',
                    'value' => function($column, $value){
                        return (new Country())->getCountryByCode($value);
                    }
                ],
                [
                    'column' => 'status',
                    'translate' => true,
                    'value' => function($column, $value){
                        return (new StatusCollection())->findByKey($value);
                    }
                ],
                [
                    'column' => 'legal_status', 
                    'translate' => true,
                    'value' => function($column, $value){
                        return (new LegalStatusCollection())->findByKey($value);
                    }
                ],
                ['column' => 'email'],
                ['column' => 'phone'],
                ['column' => 'email'],
            ]

        ], $this->translator))->render(); ?>
    </div>

    <div class="col-lg-6">
        <?= (new ListView($entity, [
            'columns' => [
                [
                    'column' => 'discount',
                    'value' => function($key, $value){
                        return $value . '%';
                    }
                ],
                ['column' => 'arrival'],
                ['column' => 'departure'],
                ['column' => 'room'],
                [
                    'column' => 'purpose',
                    'title' => 'Arrival purpose',
                    'translate' => true,
                    'value' => function($column, $value){
                        return (new PurposeCollection())->findByKey($value);
                    }
                ],
                [
                    'column' => 'payment_type',
                    'translate' => true,
                    'value' => function($column, $value){
                        return (new PaymentTypeCollection())->findByKey($value);
                    }
                ],

                [
                    'column' => 'state',
                    'title' => 'Reservation state',
                    'translate' => true,
                    'value' => function($column, $value){
                        return (new ReservationCollection())->findByKey($value);
                    }
                ],

                [
                    'column' => 'services',
                    'value' => function($column, $value){
                        return join(', ', array_column($value, 'name'));
                    }
                ],
                
                ['column' => 'comment']
            ]

        ], $this->translator))->render(); ?>
    </div>
</div>

<?php $this->loadPartial('counter'); ?>
