<?php

use Krystal\Grid\Grid;
use Krystal\Form\Element;

?>

<div class="table-responsive">
    <?= Grid::render($bookings, [
        // A column to be considered as a primary key
        'pk' => 'id',
        'batch' => false,
        'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
        'columns' => [
            [
                'column' => 'id',
                'type' => 'text',
                'label' => 'ID'
            ],
            
            [
                'column' => 'datetime',
                'type' => 'text',
                'label' => 'Date and time'
            ],

            [
                'column' => 'status',
                'type' => 'text'
            ],

            [
                'column' => 'arrival',
                'type' => 'text'
            ],
            
            [
                'column' => 'departure',
                'type' => 'text'
            ],
            
            [
                'column' => 'email',
                'type' => 'text'
            ],

            [
                'column' => 'mobile',
                'type' => 'text'
            ],
            
            [
                'column' => 'price_group',
                'type' => 'text'
            ],

            [
                'column' => 'amount',
                'value' => function($row){
                    return $row['amount'] . PHP_EOL . $row['currency'];
                }
            ]
        ],
        
        'actions' => [
            'details' => function($row){
                return Element::link('<i class="glyphicon glyphicon-search"></i>', $this->url('Site:Booking@detailsAction', $row['id']), ['class' => 'btn btn-primary']);
            }
        ]

    ], $this->translator); ?>
</div>
