<?php

use Krystal\Form\Element;
use Site\Collection\TimeRangeCollection;

?>

<div class="row">
    <div class="col-lg-10">
        <div class="row">
            <div class="col-lg-4">
                <span><? $this->show('Room types'); ?></span>
                <?= Element::select(null, $types, null, ['id' => 'type_id', 'class' => 'form-control input-sm'], null); ?>
            </div>

            <div class="col-lg-4">
                <span><? $this->show('Time range'); ?></span>
                <?= Element::select(null, $this->translateArray($timeRanges), TimeRangeCollection::PARAM_MONTH, ['id' => 'timerange', 'class' => 'form-control input-sm']); ?>
            </div>

            <div class="col-lg-4">
                <label for="autocellwidth">
                    <input type="checkbox" id="autocellwidth" /> <? $this->show('Auto cell width'); ?>
                </label>
            </div>
        </div>

        <br />

        <div id="dp"></div>
    </div>

    <div class="col-lg-2">
        <div id="nav"></div>
    </div>
</div>