<?php

use Krystal\Grid\Grid;
use Krystal\Form\Element;

?>

<h2 class="page-header"><i class="glyphicon glyphicon-home"></i> <? $this->show('Propery list'); ?></h2>


<form action="<?= $route; ?>">
    <p>
        <button class="btn btn-primary" data-form-method="GET" data-form-action="<?= $route; ?>"><i class="glyphicon glyphicon-search"></i> <? $this->show('Filter'); ?></button>
        <button class="btn btn-success" data-form-method="POST" data-form-action="<?= $this->url('Site:Property@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-disk"></i> <? $this->show('Save'); ?></button>
    </p>

    <div class="table-responsive">
        <?= Grid::render($data, [
            // A column to be considered as a primary key
            'pk' => 'id',
            'batch' => false,
            'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
            'columns' => [
                [
                    'column' => 'id',
                    'type' => 'text',
                    'label' => 'ID'
                ],

                [
                    'column' => 'name',
                    'type' => 'text',
                    'filter' => true
                ],

                [
                    'column' => 'city',
                    'type' => 'text',
                    'filter' => true
                ],

                [
                    'column' => 'address',
                    'type' => 'text',
                    'filter' => true
                ],

                [
                    'column' => 'phone',
                    'type' => 'text',
                    'filter' => true
                ],

                [
                    'column' => 'rate',
                    'type' => 'text',
                    'filter' => true
                ],

                [
                    'column' => 'website',
                    'type' => 'text',
                    'filter' => true
                ],

                [
                    'column' => 'active',
                    'type' => 'select',
                    'translateable' => true,
                    'filter' => $this->translateArray([
                        '0' => 'No',
                        '1' => 'Yes'
                    ]),
                    'value' => function($row){
                        return Element::checkbox(sprintf('active[%s]', $row['id']), $row['active'], ['class' => 'form-control']);
                    }
                ],
            ],

            'actions' => [
                'enter' => function($row){
                    return Element::link($this->translate('Enter this hotel'), $this->url('Site:Crm@hotelSwitchAction', $row['id']), ['class' => 'btn btn-success']);
                }
            ]

        ], $this->translator, $route, $query); ?>
    </div>
</form>