<?php

use Krystal\Grid\Grid;
use Krystal\Form\Element;

?>

<?php if (!$isTranslator): ?>
<p>
    <a class="btn btn-primary" href="<?= $this->url('Site:RoomBed@addAction'); ?>"><? $this->show('Add new bed'); ?></a>
</p>
<?php endif; ?>

<div class="table-response">
    <?= Grid::render($beds, [
        'pk' => 'id',
        'batch' => false,
        'columns' => [
            [
                'column' => 'id',
                'label' => '#'
            ],

            [
                'column' => 'name',
                'type' => 'text'
            ],

            [
                'column' => 'order',
                'type' => 'text'
            ]
        ],

        'actions' => [
            'edit' => function($row){
                return Element::link('<i class="glyphicon glyphicon-pencil"></i>', $this->url('Site:RoomBed@editAction', $row['id']));
            },

            'delete' => function($row) use ($isTranslator){
                if ($isTranslator === true) {
                    return null;
                }

                return Element::link('<i class="glyphicon glyphicon-remove"></i>', $this->url('Site:RoomBed@deleteAction', $row['id']), ['data-button' => 'delete']);
            }
        ]

    ], $this->translator); ?>
</div>