<?php

use Krystal\Form\Element;
use Krystal\Grid\Grid;
use Site\Service\LanguageService;;

?>

<form action="<?= $this->url('Site:Hotel@saveAction'); ?>">
    <ul class="nav nav-tabs">
        <li class="nav active"><a href="#data" data-toggle="tab"><i class="glyphicon glyphicon-pencil"></i> <? $this->show('Data'); ?></a></li>
        <li class="nav"><a href="#basic" data-toggle="tab"><i class="glyphicon glyphicon-bookmark"></i> <? $this->show('Basic'); ?></a></li>
        <li class="nav"><a href="#facilities" data-toggle="tab"><i class="glyphicon glyphicon-check"></i> <? $this->show('Facilities'); ?></a></li>
        <li class="nav"><a href="#gallery" data-toggle="tab"><i class="glyphicon glyphicon-picture"></i> <? $this->show('Gallery'); ?></a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div class="tab-pane fade in active" id="data">
            <div class="form-horizontal">
              <fieldset>
                <h3 class="text-muted"><i class="glyphicon glyphicon-pencil"></i> <? $this->show('Hotel information'); ?></h3>

                <?php $this->loadPartial('language-tabs'); ?>

                <div class="tab-content">
                    <?php foreach ($languages as $index => $language): ?>
                    <div class="tab-pane fade in <?= $index == 0 ? 'active' : null; ?>" id="<?php printf('language-%s', $language['id']); ?>" role="tabpanel">

                        <?php $entity = LanguageService::findByLangId($language['id'], $hotel); ?>

                        <?= Element::hidden(sprintf('translation[%s][id]', $language['id']), $entity['id']); ?>
                        <?= Element::hidden(sprintf('translation[%s][lang_id]', $language['id']), $language['id']); ?>

                        <?php $this->loadPartial('language-name', ['language' => $language]); ?>

                        <div class="form-group">
                          <label class="col-lg-2 control-label"><? $this->show('Name'); ?></label>
                          <div class="col-lg-10">
                            <?= Element::text(sprintf('translation[%s][name]', $language['id']), $entity['name'], array('class' => 'form-control', 'placeholder' => $this->translate('Type the full hotel name'))); ?>
                          </div>
                        </div>

                        <div class="form-group">
                          <label class="col-lg-2 control-label"><? $this->show('Address'); ?></label>
                          <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][address]', $language['id']), $entity['address'], array('class' => 'form-control', 'placeholder' => $this->translate('Type the full address'))); ?>
                          </div>
                        </div>

                        <div class="form-group">
                          <label class="col-lg-2 control-label"><? $this->show('Description'); ?></label>
                          <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][description]', $language['id']), $entity['description'], array('rows' => 10, 'class' => 'form-control', 'placeholder' => $this->translate('Type the description'))); ?>
                          </div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
              </fieldset>
            </div>
        </div>

        <div class="tab-pane fade" id="basic">
            <div class="form-horizontal">
                <fieldset>
                    <br />
                    <?= Element::hidden('hotel[id]', $entity['id']); ?>
                    <? $entity = LanguageService::normalizeEntity($entity); ?>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Hotel type'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::select('hotel[type_id]', $hotelTypes, $entity['type_id'], ['class' => 'form-control']); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Region'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::select('hotel[region_id]', $regions, $entity['region_id'], ['data-select' => 'region', 'class' => 'form-control'], false, function($key, $value){
                            return [
                                'data-region-id' => $key,
                            ];
                        }); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('District'); ?></label>
                      <div class="col-lg-10">
                        <select name="hotel[district_id]" class="form-control" data-select="district">
                        <?php foreach ($districts as $district): ?>
                        <?= Element::option($district['id'], $district['name'], ['data-region-id' => $district['region_id'], 'selected' => $district['id'] == $entity['district_id']]); ?>
                        <?php endforeach; ?>
                        </select>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Phone'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::text('hotel[phone]', $entity['phone'], array('class' => 'form-control', 'placeholder' => $this->translate('Type the phone'))); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Start price'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::text('hotel[start_price]', $entity['start_price'], array('class' => 'form-control', 'placeholder' => $this->translate('Minimal possible price of reservation'))); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Discount'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::number('hotel[discount]', $entity['discount'], array('min' => 1, 'class' => 'form-control', 'placeholder' => $this->translate('Discount loyalty if available'))); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Web-site'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::text('hotel[website]', $entity['website'], array('min' => 1, 'class' => 'form-control', 'placeholder' => $this->translate('Hotel web-site (if available)'))); ?>
                      </div>
                    </div>
                    
                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Email'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::text('hotel[email]', $entity['email'], array('class' => 'form-control', 'placeholder' => $this->translate('Hotel email'))); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Rate'); ?></label>
                      <div class="col-lg-10">
                          <?php for ($i = 1; $i < 6; $i++): ?>
                          <div class="radio">
                            <label>
                                <?= Element::radio('hotel[rate]', $i, $entity['rate'] == $i); ?> <?= $i; ?> 
                                <small class="text-muted"><?= str_repeat('<i class="glyphicon glyphicon-star"></i> ', $i); ?></small>
                            </label>
                          </div>
                          <?php endfor; ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Pick your location on map'); ?></label>
                      <div class="col-lg-10">
                        <? $this->loadPartial('map', [
                            'lat' => $entity['lat'],
                            'lng' => $entity['lng']
                        ]); ?>
                      </div>
                    </div>
                </fieldset>
            </div>
        </div>

        <div class="tab-pane fade" id="facilities">
            <? $this->loadPartial('facilities', [
                'checklist' => $checklist
            ]); ?>
        </div>

        <div class="tab-pane fade" id="gallery">
            <br />

            <p><a href="<?= $this->url('Site:Photo@addAction'); ?>" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i> <? $this->show('Add new photo'); ?></a></p>

            <?= Grid::render($photos, [
                'pk' => 'id',
                'batch' => false,
                'columns' => [
                    [
                        'column' => 'file',
                        'title' => 'Image',
                        'value' => function($row){
                            return Element::image($row['file'], ['class' => 'img-responsive']);
                        }
                    ],

                    [
                        'column' => 'cover',
                        'value' => function($row){
                            return Element::radio('cover', $row['id'], (bool) $row['cover'], ['class' => 'form-control']);
                        }
                    ],

                    [
                        'column' => 'order'
                    ]
                ],

                'actions' => [
                    'update' => function($row){
                        return Element::link('<i class="glyphicon glyphicon-pencil"></i>', $this->url('Site:Photo@editAction', $row['id']));
                    },
                    'delete' => function($row){
                        return Element::link('<i class="glyphicon glyphicon-remove"></i>', $this->url('Site:Photo@deleteAction', $row['id']));
                    }
                ]

            ], $this->translator); ?>
        </div>
    </div>

    <div class="form-group">
      <div class="pull-right">
        <button type="submit" class="btn btn-primary"><?php $this->show('Submit'); ?></button>
        <a href="<?= $this->url('Site:Reservation@tableAction', null); ?>" class="btn btn-default"><?php $this->show('Cancel'); ?></a>
      </div>
    </div>
</form>
