<?php

use Krystal\Form\Element;
use Krystal\Grid\Grid;
use Site\Service\LanguageService;;

?>

<form action="<?= $this->url('Site:Hotel@saveAction'); ?>">
    <ul class="nav nav-tabs">
        <li class="nav active"><a href="#data" data-toggle="tab"><i class="glyphicon glyphicon-pencil"></i> <? $this->show('General information'); ?></a></li>
        <li class="nav"><a href="#basic" data-toggle="tab"><i class="glyphicon glyphicon-bookmark"></i> <? $this->show('Basic'); ?></a></li>
        <li class="nav"><a href="#facilities" data-toggle="tab"><i class="glyphicon glyphicon-check"></i> <? $this->show('Facilities'); ?></a></li>
        <li class="nav"><a href="#gallery" data-toggle="tab"><i class="glyphicon glyphicon-picture"></i> <? $this->show('Gallery'); ?></a></li>
        <li class="nav"><a href="#payment" data-toggle="tab"><i class="glyphicon glyphicon-download-alt"></i> <? $this->show('Payment gateway'); ?></a></li>
        <li class="nav"><a href="#contact-person" data-toggle="tab"><i class="glyphicon glyphicon-user"></i> <? $this->show('Contact person'); ?></a></li>
        <li class="nav"><a href="#check-in-out" data-toggle="tab"><i class="glyphicon glyphicon-off"></i> <? $this->show('Check-in / Check-out'); ?></a></li>
        <li class="nav"><a href="#meals" data-toggle="tab"><i class="glyphicon glyphicon-glass"></i> <? $this->show('Meals'); ?></a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div class="tab-pane fade in active" id="data">
            <div class="form-horizontal">
              <fieldset>
                <br />

                <?php $this->loadPartial('language-tabs'); ?>

                <div class="tab-content">
                    <?php foreach ($languages as $index => $language): ?>
                    <div class="tab-pane fade in <?= $index == 0 ? 'active' : null; ?>" id="<?php printf('language-%s', $language['id']); ?>" role="tabpanel">

                        <?php $entity = LanguageService::findByLangId($language['id'], $hotel); ?>

                        <?= Element::hidden(sprintf('translation[%s][id]', $language['id']), $entity['id']); ?>
                        <?= Element::hidden(sprintf('translation[%s][lang_id]', $language['id']), $language['id']); ?>

                        <?php $this->loadPartial('language-name', ['language' => $language]); ?>

                        <div class="form-group">
                          <label class="col-lg-2 control-label"><? $this->show('Name'); ?></label>
                          <div class="col-lg-10">
                            <?= Element::text(sprintf('translation[%s][name]', $language['id']), $entity['name'], array('class' => 'form-control', 'placeholder' => $this->translate('Type the full hotel name'))); ?>
                          </div>
                        </div>

                        <div class="form-group">
                          <label class="col-lg-2 control-label"><? $this->show('Address'); ?></label>
                          <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][address]', $language['id']), $entity['address'], array('class' => 'form-control', 'placeholder' => $this->translate('Type the full address'))); ?>
                          </div>
                        </div>

                        <div class="form-group">
                          <label class="col-lg-2 control-label"><? $this->show('Description'); ?></label>
                          <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][description]', $language['id']), $entity['description'], array('rows' => 10, 'class' => 'form-control', 'placeholder' => $this->translate('Type the description'))); ?>
                          </div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
              </fieldset>
            </div>
        </div>

        <div class="tab-pane fade" id="basic">
            <div class="form-horizontal">
                <fieldset>
                    <br />
                    <?= Element::hidden('hotel[id]', $entity['id']); ?>
                    <? $entity = LanguageService::normalizeEntity($entity); ?>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Hotel type'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::select('hotel[type_id]', $hotelTypes, $entity['type_id'], ['class' => 'form-control']); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Region'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::select('hotel[region_id]', $regions, $entity['region_id'], ['data-select' => 'region', 'class' => 'form-control'], false, function($key, $value){
                            return [
                                'data-region-id' => $key,
                            ];
                        }); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('District'); ?></label>
                      <div class="col-lg-10">
                        <select name="hotel[district_id]" class="form-control" data-select="district">
                        <?php foreach ($districts as $district): ?>
                        <?= Element::option($district['id'], $district['name'], ['data-region-id' => $district['region_id'], 'selected' => $district['id'] == $entity['district_id']]); ?>
                        <?php endforeach; ?>
                        </select>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Phone'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::text('hotel[phone]', $entity['phone'], array('class' => 'form-control', 'placeholder' => $this->translate('Type the phone'))); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Fax'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::text('hotel[fax]', $entity['fax'], array('class' => 'form-control', 'placeholder' => $this->translate('Type the fax'))); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('ZIP code'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::text('hotel[zip]', $entity['zip'], array('class' => 'form-control', 'placeholder' => $this->translate('Type your ZIP code'))); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Legal name'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::text('hotel[legal_name]', $entity['legal_name'], array('class' => 'form-control', 'placeholder' => $this->translate('Type the legal organization name'))); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Legal address'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::textarea('hotel[legal_address]', $entity['legal_address'], array('class' => 'form-control', 'placeholder' => $this->translate('Type the legal organization address'))); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Discount'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::number('hotel[discount]', $entity['discount'], array('min' => 1, 'class' => 'form-control', 'placeholder' => $this->translate('Discount loyalty if available'))); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Web-site'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::text('hotel[website]', $entity['website'], array('min' => 1, 'class' => 'form-control', 'placeholder' => $this->translate('Hotel web-site (if available)'))); ?>
                      </div>
                    </div>
                    
                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Email'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::text('hotel[email]', $entity['email'], array('class' => 'form-control', 'placeholder' => $this->translate('Hotel email'))); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Hotel closed'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::checkbox('hotel[closed]', $entity['closed'], ['class' => 'form-control']); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('City tax is included in room price by default'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::checkbox('hotel[city_tax_include]', $entity['city_tax_include'], ['class' => 'form-control']); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Rate'); ?></label>
                      <div class="col-lg-10">
                          <?= Element::select('hotel[rate]', $rates, $entity['rate'], ['class' => 'form-control']); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Pick your location on map'); ?></label>
                      <div class="col-lg-10">
                        <? $this->loadPartial('map', [
                            'lat' => $entity['lat'],
                            'lng' => $entity['lng']
                        ]); ?>
                      </div>
                    </div>
                </fieldset>
            </div>
        </div>

        <div class="tab-pane fade" id="facilities">
            <? $this->loadPartial('facilities', [
                'checklist' => $checklist
            ]); ?>
        </div>

        <div class="tab-pane fade" id="gallery">
            <br />

            <p><a href="<?= $this->url('Site:Photo@addAction'); ?>" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i> <? $this->show('Add new photo'); ?></a></p>

            <?= Grid::render($photos, [
                'pk' => 'id',
                'batch' => false,
                'columns' => [
                    [
                        'column' => 'file',
                        'title' => 'Image',
                        'value' => function($row){
                            return Element::image($row['file'], ['class' => 'img-responsive']);
                        }
                    ],

                    [
                        'column' => 'cover',
                        'value' => function($row){
                            return Element::radio('cover', $row['id'], (bool) $row['cover'], ['class' => 'form-control']);
                        }
                    ],

                    [
                        'column' => 'order'
                    ]
                ],

                'actions' => [
                    'update' => function($row){
                        return Element::link('<i class="glyphicon glyphicon-pencil"></i>', $this->url('Site:Photo@editAction', $row['id']));
                    },
                    'delete' => function($row){
                        return Element::link('<i class="glyphicon glyphicon-remove"></i>', $this->url('Site:Photo@deleteAction', $row['id']));
                    }
                ]

            ], $this->translator); ?>
        </div>

        <div class="tab-pane fade" id="payment">
            <div class="form-horizontal">
                <fieldset>
                    <br />

                    <?php foreach ($payments as $system => $gateways): ?>
                    <h2 class="page-header"><i class="glyphicon glyphicon-credit-card"></i> <?= $system; ?></h2>

                    <?php foreach ($gateways as $index => $gateway): ?>
                    <?php $uniq = sprintf('field-%s', $index); ?>
                    <div class="form-group">
                      <label class="col-lg-2 control-label" for="<?= $uniq; ?>"><?= $gateway['field']; ?></label>
                      <div class="col-lg-10">
                        <?= Element::text(sprintf('payment[%s]', $gateway['field_id']), $gateway['value'], ['class' => 'form-control', 'id' => $uniq]); ?>
                      </div>
                    </div>
                    <?php endforeach; ?>

                    <?php endforeach; ?>
                </fieldset>
            </div>
        </div>

        <div class="tab-pane fade" id="contact-person">
            <div class="form-horizontal">
                <fieldset>
                    <br />

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Full name'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::text('hotel[contact_full_name]', $entity['contact_full_name'], array('class' => 'form-control', 'placeholder' => $this->translate('Type the the full name'))); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Position'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::text('hotel[contact_position]', $entity['contact_position'], array('class' => 'form-control', 'placeholder' => $this->translate('Type a position'))); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Email'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::text('hotel[contact_email]', $entity['contact_email'], array('class' => 'form-control', 'placeholder' => $this->translate('Type the email'))); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('First phone'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::text('hotel[contact_first_phone]', $entity['contact_first_phone'], array('class' => 'form-control', 'placeholder' => $this->translate('Type the first phone'))); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Second phone'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::text('hotel[contact_second_phone]', $entity['contact_second_phone'], array('class' => 'form-control', 'placeholder' => $this->translate('Type the second phone if available'))); ?>
                      </div>
                    </div>
                </fieldset>
            </div>
        </div>
        
        <div class="tab-pane fade" id="check-in-out">
            <div class="form-horizontal">
                <fieldset>
                    <br />

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Payment time'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::text('hotel[payment_time]', $entity['payment_time'], array('class' => 'form-control', 'data-plugin' => 'timepicker')); ?>
                      </div>
                    </div>

                    <section>
                        <h2 class="text-muted"><i class="glyphicon glyphicon-resize-small"></i> <? $this->show('Check-in'); ?></h2>

                        <div class="form-group">
                          <label class="col-lg-2 control-label"><? $this->show('Check-in from'); ?></label>
                          <div class="col-lg-10">
                            <?= Element::text('hotel[checkin_from]', $entity['checkin_from'], array('class' => 'form-control', 'data-plugin' => 'timepicker')); ?>
                          </div>
                        </div>

                        <div class="form-group">
                          <label class="col-lg-2 control-label"><? $this->show('Check-in to'); ?></label>
                          <div class="col-lg-10">
                            <?= Element::text('hotel[checkin_to]', $entity['checkin_to'], array('class' => 'form-control', 'data-plugin' => 'timepicker')); ?>
                          </div>
                        </div>
                    </section>

                    <section>
                        <h2 class="text-muted"><i class="glyphicon glyphicon-resize-full"></i> <? $this->show('Check-out'); ?></h2>

                        <div class="form-group">
                          <label class="col-lg-2 control-label"><? $this->show('Check-out from'); ?></label>
                          <div class="col-lg-10">
                            <?= Element::text('hotel[checkout_from]', $entity['checkout_from'], array('class' => 'form-control', 'data-plugin' => 'timepicker')); ?>
                          </div>
                        </div>

                        <div class="form-group">
                          <label class="col-lg-2 control-label"><? $this->show('Check-out to'); ?></label>
                          <div class="col-lg-10">
                            <?= Element::text('hotel[checkout_to]', $entity['checkout_to'], array('class' => 'form-control', 'data-plugin' => 'timepicker')); ?>
                          </div>
                        </div>
                    </section>
                </fieldset>
            </div>
        </div>

        <div class="tab-pane fade" id="meals">
            <div class="form-horizontal">
                <?php foreach ($meals as $meal): ?>
                <div class="checkbox">
                  <label>
                    <?= Element::checkbox(sprintf('meal[checked][%s]', $meal['id']), (bool) $meal['active'], [], false); ?>
                    <?= $meal['name']; ?>
                  </label>
                </div>
                <?php endforeach; ?>                

                <h2 class="page-header"><? $this->show('Breakfast price'); ?></h2>

                <?php foreach ($globalMealPrices as $globalMealPrice): ?>
                <?php $uniq = md5($globalMealPrice['group']); ?>

                <div class="form-group">
                  <label for="<?= $uniq; ?>" class="col-lg-2 control-label"><?= $globalMealPrice['group']; ?> (<?= $globalMealPrice['currency']; ?>)</label>
                  <div class="col-lg-10">
                    <?= Element::text(sprintf('meal[price][%s]', $globalMealPrice['price_group_id']), $globalMealPrice['price'], ['id' => $uniq, 'class' => 'form-control']); ?>
                  </div>
                </div>

                <?php endforeach; ?>
            </div>
        </div>
    </div>

    <div class="form-group">
      <div class="pull-right">
        <button type="submit" class="btn btn-primary"><?php $this->show('Submit'); ?></button>
        <a href="<?= $this->url('Site:Reservation@tableAction', null); ?>" class="btn btn-default"><?php $this->show('Cancel'); ?></a>
      </div>
    </div>
</form>
