<?php

use Krystal\Form\Element;
use Krystal\Grid\Grid;

?>

<form action="<?= $this->url('Site:Hotel@saveAction'); ?>">
    <div class="container">
        <ul class="nav nav-tabs">
            <li class="nav active"><a href="#data" data-toggle="tab"><i class="glyphicon glyphicon-pencil"></i> <? $this->show('Data'); ?></a></li>
            <li class="nav"><a href="#facilities" data-toggle="tab"><i class="glyphicon glyphicon-th-list"></i> <? $this->show('Facilities'); ?></a></li>
            <li class="nav"><a href="#gallery" data-toggle="tab"><i class="glyphicon glyphicon-picture"></i> <? $this->show('Gallery'); ?></a></li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <div class="tab-pane fade in active" id="data">
                <div class="form-horizontal">
                  <fieldset>
                    <h3 class="text-muted"> <? $this->show('Hotel information'); ?></h3>

                    <?= Element::hidden('id', $hotel['id']); ?>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Name'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::text('name', $hotel['name'], array('class' => 'form-control', 'placeholder' => $this->translate('Type the full hotel name'))); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('City'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::text('city', $hotel['city'], array('class' => 'form-control', 'placeholder' => $this->translate('Type the city name'))); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Address'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::textarea('address', $hotel['address'], array('class' => 'form-control', 'placeholder' => $this->translate('Type the full address'))); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Phone'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::text('phone', $hotel['phone'], array('class' => 'form-control', 'placeholder' => $this->translate('Type the phone'))); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Description'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::textarea('description', $hotel['description'], array('class' => 'form-control', 'placeholder' => $this->translate('Type the description'))); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Currency'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::text('currency', $hotel['currency'], array('class' => 'form-control', 'placeholder' => $this->translate('Default hotel currency'))); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 control-label"><? $this->show('Start price'); ?></label>
                      <div class="col-lg-10">
                        <?= Element::text('start_price', $hotel['start_price'], array('class' => 'form-control', 'placeholder' => $this->translate('Minimal possible price of reservation'))); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <div class="col-lg-10 col-lg-offset-2">
                        <button type="submit" class="btn btn-primary"><?php $this->show('Submit'); ?></button>
                        <button type="reset" class="btn btn-default"><?php $this->show('Cancel'); ?></button>
                      </div>
                    </div>
                  </fieldset>
                </div>
            </div>

            <div class="tab-pane fade" id="facilities">
                <?php foreach ($checklist as $category): ?>
                <div class="form-group">
                  <label class="col-lg-2 control-label"><? $this->show($category['name']); ?></label>
                  <div class="col-lg-10">
                    <?php foreach ($category['items'] as $item): ?>
                    <div class="radio">
                      <label>
                        <?= Element::checkbox(sprintf('checked[%s]', $item['id']), (bool) $item['checked'], array(), false); ?>
                        <? $this->show($item['name']); ?>
                      </label>
                    </div>
                    <?php endforeach; ?>
                  </div>
                </div>
                <?php endforeach; ?>

                <div class="form-group">
                  <div class="col-lg-10">
                    <button type="reset" class="btn btn-default"><? $this->show('Cancel'); ?></button>
                    <button type="submit" class="btn btn-primary"><? $this->show('Submit'); ?></button>
                  </div>
                </div>
            </div>

            <div class="tab-pane fade" id="gallery">
                <br />

                <p><a href="<?= $this->url('Site:Photo@addAction'); ?>" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i> <? $this->show('Add new photo'); ?></a></p>

                <?= Grid::render($photos, [
                    'pk' => 'id',
                    'batch' => false,
                    'columns' => [
                        [
                            'column' => 'file',
                            'title' => 'Image',
                            'value' => function($row){
                                return Element::image($row['file']);
                            }
                        ],
                        ['column' => 'order'],
                    ],

                    'actions' => [
                        'update' => function($row){
                            return sprintf('<a href="/photo/edit/%s"><i class="glyphicon glyphicon-pencil"></i></a>', $row['id']);
                        },
                        'delete' => function($row){
                            return sprintf('<a href="/photo/delete/%s"><i class="glyphicon glyphicon-remove"></i></a>', $row['id']);
                        }
                    ]

                ], $this->translator); ?>
            </div>
        </div>
    </div>
</form>
