<?php

use Krystal\Form\Element;

?>

<form class="form-horizontal" action="<?= $this->url('Site:Photo@saveAction'); ?>">
  <fieldset>
    <?= Element::hidden('id', $photo['id']); ?>

    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('File'); ?></label>
      <div class="col-lg-10">
        <?php if ($photo['file'] != ''): ?>
        <p><img class="img-responsive" src="<?= $photo['file']; ?>" /></p>
        <?php endif; ?>

        <?= Element::file('file', null, array('class' => 'form-control')); ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Order'); ?></label>
      <div class="col-lg-10">
        <?= Element::text('order', $photo['order'], array('class' => 'form-control')); ?>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <a href="<?= $this->url('Site:Hotel@indexAction'); ?>" class="btn btn-danger"><? $this->show('Cancel'); ?></a>
        <button type="submit" class="btn btn-primary"><? $this->show('Submit'); ?></button>
      </div>
    </div>
  </fieldset>
</form>
