<?php

use Krystal\Form\Element;

?>

<form class="form-horizontal" action="<?= $this->url('Site:Reservation@saveAction'); ?>">
  <fieldset>
	<h3 class="text-muted"> <? $this->show('Client information'); ?></h3>

    <?= Element::hidden('id', $client['id']); ?>

	<div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Full name'); ?></label>
      <div class="col-lg-10">
		<?= Element::text('full_name', $client['full_name'], array('class' => 'form-control', 'placeholder' => $this->translate('Type the full name like in the password'))); ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Gender'); ?></label>
      <div class="col-lg-10">
		<?= Element::select('gender', $this->translateArray($genders), $client['gender'], array('class' => 'form-control')); ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Country'); ?></label>
      <div class="col-lg-10">
		<?= Element::select('country', $countries, $client['country'], array('class' => 'form-control', 'data-plugin' => 'chosen')); ?>
      </div>
    </div>

	<div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Phone'); ?></label>
      <div class="col-lg-10">
		<?= Element::text('phone', $client['phone'], array('class' => 'form-control', 'placeholder' => $this->translate('Client phone with code'))); ?>
      </div>
    </div>
    
    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Status'); ?></label>
      <div class="col-lg-10">
		<?= Element::select('status', $statuses, $client['status'], array('class' => 'form-control')); ?>
      </div>
    </div>

    
    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Arrival purpose'); ?></label>
      <div class="col-lg-10">
		<?= Element::select('purpose', $this->translateArray($purposes), $client['purpose'], array('class' => 'form-control')); ?>
      </div>
    </div>
    
    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Reservation state'); ?></label>
      <div class="col-lg-10">
		<?= Element::select('state', $this->translateArray($states), $client['state'], array('class' => 'form-control')); ?>
      </div>
    </div>
	
	<h3 class="text-muted"> <? $this->show('Arrival and Departure'); ?></h3>
	
    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Arrival'); ?></label>
      <div class="col-lg-10">
		<?= Element::text('arrival', $client['arrival'], array('class' => 'form-control', 'data-plugin' => 'datetimepicker')); ?>
      </div>
    </div>

    <div class="form-group">
      <label for="inputPassword" class="col-lg-2 control-label"><? $this->show('Departure'); ?></label>
      <div class="col-lg-10">
		<?= Element::text('departure', $client['departure'], array('class' => 'form-control', 'data-plugin' => 'datetimepicker')); ?>
      </div>
    </div>

	<h3 class="text-muted"> <? $this->show('Room'); ?></h3>

    <div class="form-group">
      <label for="inputPassword" class="col-lg-2 control-label"><? $this->show('Room'); ?></label>
      <div class="col-lg-10">
		<?= Element::select('room_id', $rooms, $client['room_id'], array('class' => 'form-control')); ?>
      </div>
    </div>

	<div class="form-group">
      <label for="inputPassword" class="col-lg-2 control-label"><? $this->show('Includes'); ?></label>
      <div class="col-lg-10">
		<?= Element::select('services[]', $services, isset($client['service_ids']) ? $client['service_ids'] : null, array('class' => 'form-control', 'data-plugin' => 'chosen', 'multiple' => true)); ?>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <button type="submit" class="btn btn-primary"><?php $this->show('Submit'); ?></button>
        <button type="reset" class="btn btn-default"><?php $this->show('Cancel'); ?></button>
      </div>
    </div>
  </fieldset>
</form>
