<?php

use Krystal\Grid\Grid;
use Krystal\Form\Element;

?>

<br />

<?= Grid::render($data, array(
    // A column to be considered as a primary key
    'pk' => 'id',
    'batch' => false,
    'columns' => array(
        array(
            'column' => 'id',
            'label' => 'ID'
        ),

        array(
            'sorting' => false,
            'column' => 'country',
            'label' => 'Country',
            'type' => 'select',
            'filter' => $countries
        ),

        array(
            'column' => 'full_name',
            'type' => 'text',
            'filter' => true,
            'label' => 'Full name',
        ),

        array(
            'column' => 'room_id',
            'type' => 'select',
            'filter' => $rooms,
            'label' => 'Room',
            'value' => function($row){
                return $row['room'];
            }
        ),

        array(
            'column' => 'arrival',
            'type' => 'text',
            'filter' => true,
            'label' => 'Arrival',
        ),

        array(
            'column' => 'departure',
            'type' => 'text',
            'filter' => true,
            'label' => 'Departure',
        ),
    ),
    
    'actions' => array(
        'delete' => function($row){
            return '<a href="#"><i class="glyphicon glyphicon-remove"></i></a>';
        },
        
        'update' => function($row){
            return '<a href="#"><i class="glyphicon glyphicon-pencil"></i></a>';
        }
    )
    
)); ?>