<?php

use Krystal\Grid\Grid;
use Krystal\Form\Element;
use Krystal\Iso\ISO3166\Country;

?>

<br />

<h2 class="page-header"><i class="glyphicon glyphicon-user"></i> <? $this->show('A list of guest'); ?></h2>

<?= Grid::render($data, array(
    // A column to be considered as a primary key
    'pk' => 'id',
    'batch' => false,
    'columns' => array(
        array(
            'column' => 'id',
            'label' => 'ID'
        ),

        array(
            'sorting' => false,
            'column' => 'country',
            'label' => 'Country',
            'type' => 'select',
            'filter' => $countries,
            'value' => function($row){
                $country = new Country();
                return $country->getCountryByCode($row['country']);
            }
        ),

        array(
            'column' => 'full_name',
            'type' => 'text',
            'filter' => true,
            'label' => 'Full name',
        ),

        array(
            'column' => 'room_id',
            'type' => 'select',
            'filter' => $rooms,
            'label' => 'Room',
            'value' => function($row){
                return $row['room'];
            }
        ),

        array(
            'column' => 'arrival',
            'type' => 'text',
            'filter' => true,
            'label' => 'Arrival',
        ),

        array(
            'column' => 'departure',
            'type' => 'text',
            'filter' => true,
            'label' => 'Departure',
        ),
    ),
    
    'actions' => array(
        'delete' => function($row){
            return sprintf('<a href="/reservation/delete/%s"><i class="glyphicon glyphicon-remove"></i></a>', $row['id']);
        },
        'update' => function($row){
            return sprintf('<a href="/reservation/edit/%s"><i class="glyphicon glyphicon-pencil"></i></a>', $row['id']);
        }
    )
    
)); ?>