
<div class="container">
    <?php foreach (array_reverse($table) as $floor): ?>
    <h2><?= $floor['name']; ?></h2>

    <div class="row floor-row">
        <?php foreach (array_reverse($floor['rooms']) as $index => $room): ?>
        <? $free = empty($room['taken']); ?>

        <div class="col-lg-1 <?= !$free ? 'taken' : 'free'; ?>">
            <?php if ($free): ?>

            <p><a title="<? $this->show('Reserve'); ?>" href="<?= $this->createQueryUrl('Site:Reservation@addAction', array('room_id' => $room['id'])); ?>"><?= $room['name']; ?> <br /><small><?= $room['type']; ?></small></a></p>
            <p><? $this->show('Free'); ?></p>

            <?php else: ?>

            <p><?= $room['name']; ?> <?= $room['type']; ?></p>
            <p><? $this->show('Taken up to'); ?> <?= $room['departure']; ?></p>

            <?php endif; ?>
        </div>
        <?php endforeach; ?>
    </div>

    <?php endforeach; ?>
</div>