<?php

use Site\Service\CleaningCollection;

?>

<div class="container">
    <?php foreach (array_reverse($table) as $floor): ?>
    <h2><?= $floor['name']; ?></h2>

    <div class="row floor-row">
        <?php foreach (array_reverse($floor['rooms']) as $index => $room): ?>
        
        <?php
            $free = empty($room['taken']);
            $leavingToday = $room['leaving_today'];
            
            if ($leavingToday){
                $backgroundClass = 'leaving';
            } else {
                $backgroundClass = !$free ? 'taken' : 'free';
            }
        ?>

        <div class="col-lg-1 <?= $backgroundClass; ?>">
            <?php if ($free): ?>

            <p><a title="<? $this->show('Reserve'); ?>" href="<?= $this->createQueryUrl('Site:Reservation@addAction', array('room_id' => $room['id'])); ?>"><?= $room['name']; ?> <br /><small><?= $room['type']; ?></small></a></p>
            <p><? $this->show('Free'); ?></p>

            <?php else: ?>

            <p><?= $room['name']; ?> <br /><?= $room['type']; ?></p>

            <?php if ($leavingToday): ?>
            <a href="#" data-toggle="dropdown" class="dropdown-toggle leaving"><? $this->show('Leaving today'); ?></a>
            <?php else: ?>
            <a data-toggle="dropdown" data-toggle="tooltip" class="dropdown-toggle" href="<?= $this->url('Site:Reservation@viewTakenAction', $room['id']); ?>" title="<?= $this->translate('Remained days - %s', $room['left_days']); ?>"><? $this->show('Taken up to'); ?> <br /> <?= $room['departure']; ?></a>
            <?php endif ;?>

            <ul class="dropdown-menu">
                <li><a data-button="view" href="<?= $this->url('Site:Architecture:Room@viewAction', $room['id']); ?>"><i class="glyphicon glyphicon-list-alt"></i> <? $this->show('Room details'); ?></a></li>
                <li class="dropdown-header"><? $this->show('Reservation'); ?></li>
                <li><a data-button="view" href="<?= $this->url('Site:Reservation@viewTakenAction', $room['id']); ?>"><i class="glyphicon glyphicon-th-list"></i> <? $this->show('Reservation details'); ?></a></li>
                <li><a href="#"><i class="glyphicon glyphicon-download-alt"></i> <? $this->show('Reservation in advance'); ?></a></li>
                <li><a href="<?= $this->url('Site:Reservation@historyAction', $room['id']); ?>"><i class="glyphicon glyphicon-user"></i> <? $this->show('Reservation history'); ?></a></li>

                <li class="dropdown-header"><? $this->show('Cleaning status'); ?></li>
                <li><a href="<?= $this->url('Site:Architecture:RoomCleaning@markAction', $room['id'], CleaningCollection::CODE_CLEANED); ?>"><?php if ($room['cleaned'] == CleaningCollection::CODE_CLEANED): ?><i class="glyphicon glyphicon-ok"></i><?php endif; ?> <? $this->show('Cleaned'); ?></a></li>
                <li><a href="<?= $this->url('Site:Architecture:RoomCleaning@markAction', $room['id'], CleaningCollection::CODE_NONCLEANED); ?>"><?php if ($room['cleaned'] == CleaningCollection::CODE_NONCLEANED): ?><i class="glyphicon glyphicon-ok"></i><?php endif; ?> <? $this->show('Not cleaned'); ?></a></li>
                <li><a href="<?= $this->url('Site:Architecture:RoomCleaning@markAction', $room['id'], CleaningCollection::CODE_CHECKING); ?>"><?php if ($room['cleaned'] == CleaningCollection::CODE_CHECKING): ?><i class="glyphicon glyphicon-ok"></i><?php endif; ?> <? $this->show('Checking'); ?></a></li>
                <li><a href="<?= $this->url('Site:Architecture:RoomCleaning@markAction', $room['id'], CleaningCollection::CODE_UNDEFINED); ?>"><?php if ($room['cleaned'] == CleaningCollection::CODE_UNDEFINED): ?><i class="glyphicon glyphicon-ok"></i><?php endif; ?> <? $this->show('Undefined'); ?></a></li>
            </ul>

            <?php endif; ?>

            <?php if (CleaningCollection::CODE_CLEANED == $room['cleaned']): ?>
            <span class="cleaning-status status-clean"><? $this->show('Cleaned'); ?></span>

            <?php elseif (CleaningCollection::CODE_NONCLEANED == $room['cleaned']): ?>
            <span class="cleaning-status status-dirty"><? $this->show('Not cleaned'); ?></span>

            <?php elseif (CleaningCollection::CODE_CHECKING == $room['cleaned']): ?>
            <span class="cleaning-status status-checking"><? $this->show('Checking'); ?></span>

            <?php endif; ?>
        </div>
        <?php endforeach; ?>
    </div>

    <?php endforeach; ?>
</div>

<? $this->loadPartial('client-modal'); ?>
