<?php

use Krystal\Grid\Grid;
use Krystal\Form\Element;

?>

<p>
    <a class="btn btn-success" href="<?= $this->url('Site:Dictionary@addAction'); ?>"><i class="glyphicon glyphicon-floppy-disk"></i> <? $this->show('Add'); ?></a>
</p>

<div class="table-responsive">
    <?= Grid::render($entries, [
        // A column to be considered as a primary key
        'pk' => 'id',
        'batch' => false,
        'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
        'columns' => [
            [
                'column' => 'id',
                'type' => 'text',
                'label' => 'ID'
            ],

            [
                'column' => 'value',
                'type' => 'text'
            ],

            [
                'column' => 'alias',
                'type' => 'text'
            ]
        ],

        'actions' => [
            'edit' => function($row){
                return Element::link('<i class="glyphicon glyphicon-pencil"></i>', $this->url('Site:Dictionary@editAction', $row['id']));
            },

            'delete' => function($row){
                return Element::link('<i class="glyphicon glyphicon-remove"></i>', $this->url('Site:Dictionary@deleteAction', $row['id']), ['data-button' => 'delete']);
            }
        ]

    ], $this->translator); ?>
</div>
