<?php

use Krystal\Form\Element;

?>

<form class="form-horizontal" method="POST">
  <fieldset>
    <legend><i class="glyphicon glyphicon-flash"></i> <? $this->show('Change password'); ?></legend>

    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('New password'); ?></label>
      <div class="col-lg-10">
        <?= Element::password('password', null, ['class' => 'form-control', 'placeholder' => $this->translate('Type new password')]); ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('New password confirmation'); ?></label>
      <div class="col-lg-10">
        <?= Element::password('confirmation', null, ['class' => 'form-control', 'placeholder' => $this->translate('Type new password again')]); ?>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <button type="submit" class="btn btn-primary"><? $this->show('Submit'); ?></button>
      </div>
    </div>
  </fieldset>
</form>