<?php

use Krystal\Db\Filter\InputDecorator;
use Krystal\Form\Element;

$entity = new InputDecorator($entity);

?>

<form class="form-horizontal" action="<?= $this->url('Site:Architecture:Room@saveAction'); ?>">
  <fieldset>
    <legend><? $this->show($entity['id'] ? 'Edit the room' : 'Add a room'); ?></legend>

    <?= Element::hidden('id', $entity['id']); ?>

    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Name'); ?></label>
      <div class="col-lg-10">
        <?= Element::text('name', $entity['name'], array('class' => 'form-control')); ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Floor'); ?></label>
      <div class="col-lg-10">
        <?= Element::select('floor_id', $floors, $entity['floor_id'], array('class' => 'form-control')); ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Maximal person amount'); ?></label>
      <div class="col-lg-10">
        <?= Element::number('persons', $entity['persons'], array('class' => 'form-control', 'min' => 1)); ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Room type'); ?></label>
      <div class="col-lg-10">
        <?= Element::select('type_id', $roomTypes, $entity['type_id'], array('class' => 'form-control')); ?>
      </div>
    </div>
    
    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Square'); ?></label>
      <div class="col-lg-10">
        <?= Element::number('square', $entity['square'], array('class' => 'form-control', 'min' => 0, 'step' => '0.01', 'placeholder' => $this->translate('Square of the room'))); ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Room quality status'); ?></label>
      <div class="col-lg-10">
        <?= Element::select('quality', $this->translateArray($roomQualities), $entity['quality'], array('class' => 'form-control')); ?>
      </div>
    </div>
    
    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Cleaning status'); ?></label>
      <div class="col-lg-10">
        <?= Element::select('cleaned', $this->translateArray($cleaningCollection->getAll()), $entity['cleaned'], array('class' => 'form-control')); ?>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <a href="<?= $this->url('Site:Architecture:Grid@indexAction'); ?>" class="btn btn-danger"><? $this->show('Cancel'); ?></a>
        <button type="submit" class="btn btn-primary"><? $this->show('Submit'); ?></button>
      </div>
    </div>
  </fieldset>
</form>
