<?php

use Krystal\Db\Filter\InputDecorator;
use Krystal\Form\Element;

$entity = new InputDecorator($entity);

?>

<form class="form-horizontal" action="<?= $this->url('Site:Architecture:Room@saveAction'); ?>">
  <fieldset>
    <legend>Edit record</legend>

    <?= Element::hidden('id', $entity['id']); ?>

    <div class="form-group">
      <label class="col-lg-2 control-label">Name</label>
      <div class="col-lg-10">
        <?= Element::text('name', $entity['name'], array('class' => 'form-control')); ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-lg-2 control-label">Floor</label>
      <div class="col-lg-10">
        <?= Element::select('floor_id', $floors, $entity['floor_id'], array('class' => 'form-control')); ?>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <a href="<?= $this->url('Site:Architecture:Grid@indexAction'); ?>" class="btn btn-danger">Cancel</a>
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </fieldset>
</form>
