
<div class="list-group">
  <a href="#" class="list-group-item">
    <h4 class="list-group-item-heading"><? $this->show('Total days'); ?></h4>
    <p class="list-group-item-text"><span data-count="days"><?= isset($entity['days']) ? $entity['days'] : 0; ?></span></p>
  </a>
  <a href="#" class="list-group-item">
    <h4 class="list-group-item-heading"><? $this->show('Discount'); ?></h4>
    <p class="list-group-item-text"><span data-count="discount"><?= isset($entity['discount']) ? $entity['discount'] : 0; ?></span> <span>%</span></p>
  </a>

  <a href="#" class="list-group-item">
    <h4 class="list-group-item-heading"><? $this->show('Daily tax'); ?></h4>
    <p class="list-group-item-text"><span data-count="daily-tax"><?= isset($entity['tax']) ? $entity['tax'] : 0; ?></span> <span data-count="currency"><?= isset($entity['currency']) ? $entity['currency'] : null; ?></span></p>
  </a>
  
  <a href="#" class="list-group-item">
    <h4 class="list-group-item-heading"><? $this->show('Total price'); ?></h4>
    <p class="list-group-item-text"><span data-count="price"><?= isset($entity['price']) ? $entity['price'] : 0; ?></span> <span data-count="currency"><?= isset($entity['currency']) ? $entity['currency'] : null; ?></span></p>
  </a>
</div>
