<div class="list-group">
  <a href="#" class="list-group-item">
    <h4 class="list-group-item-heading"><? $this->show('Total days'); ?></h4>
    <p class="list-group-item-text"><span data-count="days"><?= isset($count['days']) ? $count['days'] : 0; ?></span></p>
  </a>
  <a href="#" class="list-group-item">
    <h4 class="list-group-item-heading"><? $this->show('Discount'); ?></h4>
    <p class="list-group-item-text"><span data-count="discount"><?= isset($count['discount']) ? $count['discount'] : 0; ?></span> <span>%</span></p>
  </a>
  <a href="#" class="list-group-item">
    <h4 class="list-group-item-heading"><? $this->show('Total price'); ?></h4>
    <p class="list-group-item-text"><span data-count="price"><?= isset($count['price']) ? $count['price'] : 0; ?></span> <?= $currency; ?></p>
  </a>
</div>
