<?php

use Krystal\Form\Element;

$options = [
    '1' => 'Yes, free of charge', 
    '0' => 'Yes, but not free'
];

?>

<?php foreach ($checklist as $category): ?>
<div class="form-group">
  <label class="col-lg-2 control-label"><? $this->show($category['name']); ?> <small class="text-muted">(<?= $category['item_count']; ?>)</small></label>
  <div class="col-lg-10">
    <?php foreach ($category['items'] as $item): ?>
    <div class="radio">
      <label class="facility-radio">
        <?= Element::checkbox(sprintf('checked[%s]', $item['id']), (bool) $item['checked'], array(), false); ?>
        <? $this->show($item['name']); ?>
      </label>

      <?php if (!$item['always_free']): ?>
      <span class="facility-container <?= $item['checked'] ? null : 'hidden'; ?>">
        <?= Element::select(null, $this->translateArray($options), null, ['class' => 'form-control']); ?>
      </span>
      <?php endif; ?>
    </div>
    <?php endforeach; ?>
  </div>
</div>
<?php endforeach; ?>