
<button type="submit" class="btn btn-primary"><?php $this->show('Submit'); ?></button>
<?php if ($client['id']): ?>
<a href="<?= $this->url('Site:ReservationService@indexAction', $client['id']); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-tag"></i> <? $this->show('Manage services'); ?></a>
<?php endif; ?>
<a href="#" data-button="back" class="btn btn-info hidden-print"><i class="glyphicon glyphicon-chevron-left"></i> <?php $this->show('Back'); ?></a>
