<?php

use Krystal\Form\Element;

?>

<h2 class="page-header"><i class="glyphicon glyphicon-tags"></i> <? $this->show('Services'); ?> <small>(<?= count($services); ?>)</small></h2>

<div class="row">
    <div class="col-lg-6">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th><?php $this->show('Name'); ?></th>
                    <th><?php $this->show('Price'); ?></th>
                    <th><?php $this->show('Unit'); ?></th>
                    <th><?php $this->show('Actions'); ?></th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($services as $index => $service): ?>
                <tr class="<?= $service['id'] == $id ? 'success' : null; ?>">
                    <td><?= $index + 1; ?></td>
                    <td><?= $service['name']; ?></td>
                    <td><?= number_format($service['price']), PHP_EOL, $currency; ?></td>
                    <td><?php $this->show($unitCollection->findByKey($service['unit'])); ?></td>
                    <td>
                        <a href="<?= $this->url('Site:Service@editAction', $service['id']); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                        <a href="<?= $this->url('Site:Service@deleteAction', $service['id']); ?>"><i class="glyphicon glyphicon-remove"></i></a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <div class="col-lg-6">
        <form class="form-horizontal" action="<?= $this->url('Site:Service@saveAction'); ?>">
          <fieldset>
            <legend><i class="glyphicon glyphicon-pencil"></i> <?php $this->show(!$entity['id'] ? 'Add a service' : 'Edit the service'); ?></legend>

            <?= Element::hidden('id', $entity['id']); ?>

            <div class="form-group">
              <label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
              <div class="col-lg-10">
                <?= Element::text('name', $entity['name'], array('class' => 'form-control')); ?>
              </div>
            </div>

            <div class="form-group">
              <label class="col-lg-2 control-label"><?php $this->show('Price'); ?></label>
              <div class="col-lg-10">
                <?= Element::number('price', $entity['price'], array('class' => 'form-control', 'step' => '0.01')); ?>
              </div>
            </div>

            <div class="form-group">
              <label class="col-lg-2 control-label"><?php $this->show('Unit'); ?></label>
              <div class="col-lg-10">
                <?= Element::select('unit', $this->translateArray($unitCollection->getAll()), $entity['unit'], array('class' => 'form-control')); ?>
              </div>
            </div>

            <div class="form-group">
              <label class="col-lg-2 control-label"><?php $this->show('Comment'); ?></label>
              <div class="col-lg-10">
                <?= Element::text('comment', $entity['comment'], array('class' => 'form-control')); ?>
              </div>
            </div>

            <div class="form-group">
              <div class="col-lg-10 col-lg-offset-2">
                <button type="submit" class="btn btn-primary"><?php $this->show('Submit'); ?></button>
                <a href="<?= $this->url($entity['id'] ? 'Site:Service@indexAction' : 'Site:Architecture:Grid@indexAction'); ?>" class="btn btn-danger"><?php $this->show('Back'); ?></a>
              </div>
            </div>
          </fieldset>
        </form>
    </div>
</div>
