<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="csrf-token" content="<?php echo $csrfToken; ?>" />
    <title>Krystal Framework: You're ready to start!</title>
    
    <?php foreach ($this->getPluginBag()->getStylesheets() as $path): ?>
    <link href="<?php echo $path; ?>" rel="stylesheet" />
    <?php endforeach; ?>
  </head>
  <body role="document">
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Project</a>
        </div>
        
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><? $this->show('Reservation'); ?> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="<?= $this->url('Site:Reservation@tableAction'); ?>"><?php $this->show('Desktop'); ?></a></li>
                <li><a href="<?= $this->url('Site:Reservation@indexAction'); ?>"><?php $this->show('Current guests'); ?></a></li>
                <li class="dropdown-header"><? $this->show('Management'); ?></li>
                <li><a href="<?= $this->url('Site:Reservation@addAction'); ?>"><?php $this->show('New reservation'); ?></a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><? $this->show('My hotel'); ?> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="<?= $this->url('Site:Architecture:Grid@indexAction'); ?>"><? $this->show('Architecture'); ?></a></li>
                <li><a href="<?= $this->url('Site:Architecture:RoomType@indexAction'); ?>"><? $this->show('Room types'); ?></a></li>
                <li><a href="<?= $this->url('Site:Inventory@indexAction'); ?>"><? $this->show('Inventory'); ?></a></li>
              </ul>
            </li>
            <?php if (!$isLoggedIn): ?>
            <li><a href="<?php echo $this->url('Site:Auth@indexAction'); ?>"><?php $this->show('Login'); ?></a></li>
            <?php else: ?>
            <li><a href="<?php echo $this->url('Site:Auth@logoutAction'); ?>"><?php $this->show('Logout'); ?></a></li>
            <?php endif; ?>
            
          </ul>        
        </div>
      </div>
    </nav>
    
    <div class="container" role="main">
        <?php if ($flashBag->has('success')): ?>
        <div class="alert alert-success" role="alert"><i class="glyphicon glyphicon-ok"></i> <?= $flashBag->get('success'); ?></div>
        <?php endif; ?>

        <?php if ($flashBag->has('warning')): ?>
        <div class="alert alert-warning" role="alert"><i class="glyphicon glyphicon-ok"></i> <?= $flashBag->get('warning'); ?></div>
        <?php endif; ?>
        
        <?php $this->loadPartial('breadcrumbs'); ?>

        <?php echo $fragment; ?>
    </div>
    
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <?php foreach ($this->getPluginBag()->getScripts() as $script): ?>
    <script src="<?php echo $script; ?>"></script>
    <?php endforeach;?>
  </body>
</html>