
<div class="row">
    <div class="col-lg-4">
        <div class="list-group">
          <?php foreach($stat as $name => $value): ?>
          <a href="#" class="list-group-item">
            <h4 class="list-group-item-heading"><? $this->show($name); ?></h4>
            <p class="list-group-item-text"><?= $value; ?></span></p>
          </a>
          <?php endforeach; ?>
        </div>
    </div>
</div>