<?php

use Krystal\Grid\Grid;
use Krystal\Form\Element;

$data = array(
    array(
        'id' => '1',
        'active' => '1',
        'name' => 'Dave',
        'age' => '24',
        'location' => 'Sweden'
    ),

    array(
        'id' => '2',
        'active' => '1',
        'name' => 'Dave',
        'age' => '25',
        'location' => 'United Kindom'
    ),

    array(
        'id' => '3',
        'active' => '0',
        'name' => 'Rod',
        'age' => '25',
        'location' => 'United States'
    ),
    
);

?>

<br />
<br />
<br />

<?php echo Grid::render($data, array(
    // A column to be considered as a primary key
    'pk' => 'id',
    'batch' => false,
    'columns' => array(
        array(
            'column' => 'id',
            'label' => 'ID'
        ),

        array(
            'sorting' => false,
            'column' => 'active',
            'label' => 'Active',
            'type' => 'select',
            'editable' => true,
            'filter' => array(
                '1' => 'Yes',
                '0' => 'No'
            )
        ),
        
        array(
            'column' => 'name',
            'type' => 'text',
            'filter' => true,
            'label' => 'Name',
        ),

        array(
            'column' => 'age',
            'type' => 'text',
            'filter' => false,
            'editable' => false,
            'label' => 'Age',
            'attrs' => array(
                // 
            )
        ),

        array(
            'column' => 'location',
            'label' => 'Location',
            'type' => 'text',
            'filter' => true,
            'editable' => false,
            'attrs' => array(
                // 
            )
        )
    ),
    
    'actions' => array(
        'delete' => function($row){
            return '<a href="#"><i class="glyphicon glyphicon-remove"></i></a>';
        },
        
        'update' => function($row){
            return '<a href="#"><i class="glyphicon glyphicon-pencil"></i></a>';
        }
    )
    
)); ?>