<?php

use Krystal\Form\Element;
use Site\Service\LanguageService;

?>

<form class="form-horizontal" action="<?= $this->url('Site:Architecture:RoomType@saveAction'); ?>">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#configuration" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Configuration'); ?></a></li>
        <li role="presentation"><a href="#category" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Description'); ?></a></li>
        <li class="nav"><a href="#facilities" data-toggle="tab"><i class="glyphicon glyphicon-check"></i> <? $this->show('Facilities'); ?></a></li>
        <li role="presentation"><a href="#beds" data-toggle="tab"><i class="glyphicon glyphicon-check"></i> <? $this->show('Beds'); ?></a></li>
	</ul>

    <div class="tab-content">
        <div class="tab-pane fade in" id="category" role="tabpanel">
            <div class="well">
                <?php $this->loadPartial('language-tabs'); ?>

                <div class="tab-content">
                    <?php foreach ($languages as $index => $language): ?>
                    <div class="tab-pane fade in <?= $index == 0 ? 'active' : null; ?>" id="<?php printf('language-%s', $language['id']); ?>" role="tabpanel">
                        <?php $entity = LanguageService::findByLangId($language['id'], $type); ?>

                        <?= Element::hidden(sprintf('translation[%s][id]', $language['id']), $entity['id']); ?>
                        <?= Element::hidden(sprintf('translation[%s][lang_id]', $language['id']), $language['id']); ?>

                        <?php $this->loadPartial('language-name', ['language' => $language]); ?>

                        <div class="form-group">
                          <div class="col-lg-12">
                            <?= Element::textarea(sprintf('translation[%s][description]', $language['id']), $entity['description'], ['rows' => 7, 'class' => 'form-control', 'placeholder' => $this->translate('Describe the type of the room')]); ?>
                          </div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>

        <div class="tab-pane fade in active" id="configuration" role="tabpanel">
          <div class="well">
            <?= Element::hidden('type[id]', $entity['id']); ?>

            <div class="form-group">
              <label class="col-lg-2 control-label"><?php $this->show('Type'); ?></label>
              <div class="col-lg-10">
                <?= Element::select('type[category_id]', $categories, $entity['category_id'], ['class' => 'form-control']); ?>
              </div>
            </div>

            <div class="form-group">
              <label class="col-lg-2 control-label"><?php $this->show('Persons'); ?></label>
              <div class="col-lg-10">
                <?= Element::number('type[persons]', $entity['persons'], ['min' => 1, 'class' => 'form-control', 'placeholder' => $this->translate('Maximal capacity')]); ?>
              </div>
            </div>

            <div class="form-group">
              <label class="col-lg-2 control-label"><?php $this->show('Children capacity'); ?></label>
              <div class="col-lg-10">
                <?= Element::select('type[children]', $this->translateArray($children), $entity['children'], ['class' => 'form-control']); ?>
              </div>
            </div>

            <h2 class="text-muted"><i class="glyphicon glyphicon-sort"></i> <? $this->show('Price policy'); ?></h2>

            <?php foreach ($priceGroups as $capacity => $group): ?>
            <section class="price-policy-wrapper">
                <div class="form-group">
                  <label class="col-lg-2 control-label"><? $this->show('Number of people'); ?></label>
                  <div class="col-lg-10">
                    <div class="input-group">
                        <?= Element::number('price_group_ids[capacity][]', $capacity, array('class' => 'form-control')); ?>
                        <span class="input-group-addon"><a data-button="price-policy-delete" href="#"><i class="glyphicon glyphicon-remove"></i></a></span>
                    </div>
                  </div>
                </div>

                <?php foreach ($group as $item): ?>
                <div class="form-group">
                  <label class="col-lg-2 control-label"><strong><? $this->show('Price'); ?> (<?= $item['currency']; ?>)</strong> <?= $item['name']; ?></label>
                  <div class="col-lg-10">
                    <?= Element::number(sprintf('price_group_ids[group][%s][]', $item['id']), isset($item['price']) ? $item['price'] : null, array('class' => 'form-control')); ?>
                  </div>
                </div>
                <?php endforeach; ?>
                
                <hr />
            </section>

            <?php endforeach; ?>
          </div>
        </div>

        <div class="tab-pane fade" id="facilities">
            <? $this->loadPartial('facilities', [
                'checklist' => $checklist
            ]); ?>
        </div>

        <div class="tab-pane fade" id="beds">
            <div class="well">
                <?php foreach ($beds as $bed): ?>
                <div class="form-group">
                  <label class="col-lg-2 control-label"><?= $bed['name']; ?></label>
                  <div class="col-lg-10">
                    <?= Element::number(sprintf('beds[%s]', $bed['id']), $bed['qty'] ?? null, ['class' => 'form-control', 'min' => 0]); ?>
                  </div>
                </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <button type="submit" class="btn btn-primary"><?php $this->show('Submit'); ?></button>
        <button type="button" class="btn btn-success" data-button="price-policy-add"><i class="glyphicon glyphicon-share"></i> <? $this->show('Add price policy'); ?></button>
        <a href="<?= $this->url($entity['id'] ? 'Site:Architecture:RoomType@indexAction' : 'Site:Architecture:Grid@indexAction'); ?>" class="btn btn-danger"><?php $this->show('Cancel'); ?></a>
      </div>
    </div>
</form>
