<?php

use Krystal\Form\Element;

?>

<form class="form-horizontal" action="<?= $this->url('Site:Architecture:RoomType@saveAction'); ?>">
  <fieldset>
    <legend><i class="glyphicon glyphicon-pencil"></i> <?php $this->show(!$entity['id'] ? 'Add new room type' : 'Edit room type'); ?></legend>

    <?= Element::hidden('id', $entity['id']); ?>

    <div class="form-group">
      <label class="col-lg-2 control-label"><?php $this->show('Type'); ?></label>
      <div class="col-lg-10">
        <?= Element::select('category_id', $categories, $entity['category_id'], ['class' => 'form-control']); ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-lg-2 control-label"><?php $this->show('Persons'); ?></label>
      <div class="col-lg-10">
        <?= Element::number('persons', $entity['persons'], ['min' => 1, 'class' => 'form-control', 'placeholder' => $this->translate('Maximal capacity')]); ?>
      </div>
    </div>

    <?php foreach ($priceGroups as $priceGroup): ?>
    <div class="form-group">
      <label class="col-lg-2 control-label"><strong><? $this->show('Price'); ?> (<?= $priceGroup['currency']; ?>)</strong> <?= $priceGroup['name']; ?></label>
      <div class="col-lg-10">
        <?= Element::number(sprintf('price_group_ids[%s]', $priceGroup['id']), isset($priceGroup['price']) ? $priceGroup['price'] : null, array('class' => 'form-control')); ?>
      </div>
    </div>
    <?php endforeach; ?>
    
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <button type="submit" class="btn btn-primary"><?php $this->show('Submit'); ?></button>
        <a href="<?= $this->url($entity['id'] ? 'Site:Architecture:RoomType@indexAction' : 'Site:Architecture:Grid@indexAction'); ?>" class="btn btn-danger"><?php $this->show('Cancel'); ?></a>
      </div>
    </div>
  </fieldset>
</form>
