<?php

use Krystal\Form\Element;

$this->loadPartial('hint', [
    'lines' => [
        'Add all possible room types and their prices available in your hotel.',
        'You can then attach created types to rooms to be created.'
    ]
]);

?>

<?php if (!$isTranslator): ?>
<p>
    <a class="btn btn-primary" href="<?= $this->url('Site:Architecture:RoomType@addAction'); ?>"><? $this->show('Add room type'); ?></a>
    <a class="btn btn-success" href="<?= $this->url('Site:Architecture:Room@indexAction'); ?>"><? $this->show('Architecture'); ?></a>
</p>
<?php endif; ?>

<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th><?php $this->show('Name'); ?></th>
                <th class="col-lg-1"><?php $this->show('Room count'); ?></th>
                <th><?php $this->show('Persons'); ?></th>
                <th><?php $this->show('Children capacity'); ?></th>
                <th class="col-lg-3"><?php $this->show('Prices'); ?></th>
                <th class="col-lg-3"><?php $this->show('Description'); ?></th>
                <th><?php $this->show('Actions'); ?></th>
            </tr>
        </thead>

        <tbody>
            <?php foreach ($types as $index => $type): ?>
            <tr>
                <td><?= $index + 1; ?></td>
                <td><?= $type['name']; ?></td>
                <td><?= $type['room_count']; ?></td>
                <td>
                    <?= str_repeat('<i class="glyphicon glyphicon-user"></i> ', $type['persons']); ?>
                </td>
                <td>
                    <?php if ($type['children'] > 0): ?>
                    <?= str_repeat('<i class="glyphicon glyphicon-user"></i> ', $type['children']); ?>
                    <?php else: ?>
                    <em><? $this->show('Without children'); ?></em>
                    <?php endif; ?>
                </td>
                <td>
                    <?php foreach ($type['prices'] as $price): ?>
                    <p>
                        <span class="text-muted"><?= str_repeat('<i class="glyphicon glyphicon-user"></i> ', $price['capacity']); ?></span>
                        <?= sprintf('%s - %s %s', $price['name'], number_format($price['price']), $price['currency']); ?>
                    </p>
                    <?php endforeach; ?>
                </td>
                <td class="col-lg-3"><?= $type['description']; ?></td>
                <td>
                    <a href="<?= $this->url('Site:Architecture:RoomType@editAction', $type['id']); ?>"><i class="glyphicon glyphicon-pencil"></i></a>

                    <?php if (!$isTranslator): ?>
                    <a data-button="delete" href="<?= $this->url('Site:Architecture:RoomType@deleteAction', $type['id']); ?>"><i class="glyphicon glyphicon-remove"></i></a>
                    <?php endif; ?>

                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
