<?php

use Krystal\Form\Element;

$this->loadPartial('hint', [
    'lines' => [
        'Create all inventory available in your object.',
        'Later on, you can attach it to rooms.'
    ]
]);

?>

<div class="row">
    <div class="col-lg-6">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th><?php $this->show('Name'); ?></th>
                    <th><?php $this->show('Actions'); ?></th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($inventories as $index => $inventory): ?>
                <tr class="<?= $inventory['id'] == $id ? 'success' : null; ?>">
                    <td><?= $index + 1; ?></td>
                    <td><?= $inventory['name']; ?></td>
                    <td>
                        <a href="<?= $this->url('Site:Inventory@editAction', $inventory['id']); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                        <a data-button="delete" href="<?= $this->url('Site:Inventory@deleteAction', $inventory['id']); ?>"><i class="glyphicon glyphicon-remove"></i></a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <div class="col-lg-6">
        <form class="form-horizontal" action="<?= $this->url('Site:Inventory@saveAction'); ?>">
          <fieldset>
            <legend><i class="glyphicon glyphicon-pencil"></i> <?php $this->show(!$entity['id'] ? 'Add an inventory' : 'Edit the inventory'); ?></legend>

            <?= Element::hidden('id', $entity['id']); ?>

            <div class="form-group">
              <label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
              <div class="col-lg-10">
                <?= Element::text('name', $entity['name'], array('class' => 'form-control', 'placeholder' => $this->translate('For example - Cupboard or Safe'))); ?>
              </div>
            </div>

            <div class="form-group">
              <div class="col-lg-10 col-lg-offset-2">
                <button type="submit" class="btn btn-primary"><?php $this->show('Submit'); ?></button>

                <?php if ($entity['id']): ?>
                <a href="<?= $this->url('Site:Inventory@indexAction'); ?>" class="btn btn-danger"><?php $this->show('Cancel'); ?></a>
                <?php endif; ?>

              </div>
            </div>
          </fieldset>
        </form>
    </div>
</div>
