<?php

use Krystal\Form\Element;

?>

<h2 class="page-header"><i class="glyphicon glyphicon-flag"></i> <? $this->show('Languages'); ?> <small>(<?= count($languages); ?>)</small></h2>

<div class="row">
    <div class="col-lg-6">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th><?php $this->show('Name'); ?></th>
                    <th><?php $this->show('Code'); ?></th>
                    <th><?php $this->show('Actions'); ?></th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($languages as $language): ?>
                <tr class="<?= $language['id'] == $entity['id'] ? 'success' : null; ?>">
                    <td><?= $language['id']; ?></td>
                    <td><?= $language['name']; ?></td>
                    <td><?= $language['code']; ?></td>
                    <td>
                        <a href="<?= $this->url('Site:Language@editAction', $language['id']); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                        <a data-button="delete" href="<?= $this->url('Site:Language@deleteAction', $language['id']); ?>"><i class="glyphicon glyphicon-remove"></i></a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <div class="col-lg-6" role="box">
        <form class="form-horizontal" action="<?= $this->url('Site:Language@saveAction'); ?>">
          <fieldset>
            <legend><i class="glyphicon glyphicon-pencil"></i> <?php $this->show(!$entity['id'] ? 'Add a language' : 'Edit the language'); ?></legend>

            <?= Element::hidden('id', $entity['id']); ?>

            <div class="form-group">
              <label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
              <div class="col-lg-10">
                <?= Element::text('name', $entity['name'], array('class' => 'form-control')); ?>
              </div>
            </div>

            <div class="form-group">
              <label class="col-lg-2 control-label"><?php $this->show('Code'); ?></label>
              <div class="col-lg-10">
                <?= Element::text('code', $entity['code'], array('class' => 'form-control')); ?>
              </div>
            </div>

            <div class="form-group">
              <div class="col-lg-10 col-lg-offset-2">
                <button type="submit" class="btn btn-primary"><?php $this->show('Submit'); ?></button>

                <?php if ($entity['id']): ?>
                <a href="<?= $this->url('Site:Languages@indexAction'); ?>" class="btn btn-danger"><?php $this->show('Cancel'); ?></a>
                <?php endif; ?>

              </div>
            </div>
          </fieldset>
        </form>
    </div>
</div>
