<?php

use Krystal\Form\Element;

$this->loadPartial('hint', [
    'lines' => [
        'Create all possible extra services your object offers',
        'Later on, you can attach them to new reservations'
    ]
]);

?>

<div class="row">
    <div class="col-lg-6">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th><?php $this->show('Name'); ?></th>
                    <th><?php $this->show('Price'); ?></th>
                    <th><?php $this->show('Unit'); ?></th>
                    <th><?php $this->show('Comment'); ?></th>
                    <th><?php $this->show('Actions'); ?></th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($services as $index => $service): ?>
                <tr class="<?= $service['id'] == $id ? 'success' : null; ?>">
                    <td><?= $index + 1; ?></td>
                    <td><?= $service['name']; ?></td>
                    <td>
                        <?php foreach ($service['prices'] as $price): ?>
                        <p><?= sprintf('%s - %s %s', $price['name'], number_format($price['price']), $price['currency']); ?></p>
                        <?php endforeach; ?>
                    </td>
                    <td><?php $this->show($unitCollection->findByKey($service['unit'])); ?></td>
                    <td><?= $service['comment']; ?></td>
                    <td>
                        <a href="<?= $this->url('Site:Service@editAction', $service['id']); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                        <a data-button="delete" href="<?= $this->url('Site:Service@deleteAction', $service['id']); ?>"><i class="glyphicon glyphicon-remove"></i></a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <div class="col-lg-6">
        <form class="form-horizontal" action="<?= $this->url('Site:Service@saveAction'); ?>">
          <fieldset>
            <legend><i class="glyphicon glyphicon-pencil"></i> <?php $this->show(!$entity['id'] ? 'Add a service' : 'Edit the service'); ?></legend>

            <?= Element::hidden('id', $entity['id']); ?>

            <div class="form-group">
              <label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
              <div class="col-lg-10">
                <?= Element::text('name', $entity['name'], array('class' => 'form-control', 'placeholder' => $this->translate('Type service name. For example - Transfer or Massage'))); ?>
              </div>
            </div>

            <div class="form-group">
              <label class="col-lg-2 control-label"><?php $this->show('Unit'); ?></label>
              <div class="col-lg-10">
                <?= Element::select('unit', $this->translateArray($unitCollection->getAll()), $entity['unit'], array('class' => 'form-control')); ?>
              </div>
            </div>

            <div class="form-group">
              <label class="col-lg-2 control-label"><?php $this->show('Comment'); ?></label>
              <div class="col-lg-10">
                <?= Element::text('comment', $entity['comment'], array('class' => 'form-control')); ?>
              </div>
            </div>

            <?php foreach ($priceGroups as $priceGroup): ?>
            <div class="form-group">
              <label class="col-lg-2 control-label"><strong><? $this->show('Price'); ?> (<?= $priceGroup['currency']; ?>)</strong> <?= $priceGroup['name']; ?></label>
              <div class="col-lg-10">
                <?= Element::number(sprintf('price_group_ids[%s]', $priceGroup['id']), isset($priceGroup['price']) ? $priceGroup['price'] : null, array('class' => 'form-control')); ?>
              </div>
            </div>
            <?php endforeach; ?>

            <div class="form-group">
              <div class="col-lg-10 col-lg-offset-2">
                <button type="submit" class="btn btn-primary"><?php $this->show('Submit'); ?></button>

                <?php if ($entity['id']): ?>
                <a href="<?= $this->url('Site:Service@indexAction'); ?>" class="btn btn-danger"><?php $this->show('Cancel'); ?></a>
                <?php endif; ?>

              </div>
            </div>
          </fieldset>
        </form>
    </div>
</div>
