<?php

use Krystal\Grid\Grid;
use Krystal\Form\Element;
use Krystal\Iso\ISO3166\Country;

?>

<form action="<?= $route; ?>">
    <div class="summary">
        <h4 class="page-header">
            <?php if ($paginator->getSummary() != 0): ?>
            <small> (<?php $this->show('Displayed'); ?> <?= $paginator->getSummary(); ?> <?php $this->show('of'); ?> <?= $paginator->getTotalAmount(); ?>) </small>
            <?php endif; ?>
        </h4>

        <button class="btn btn-danger" href="<?= $this->url('Site:Transaction@clearAction'); ?>" data-button="delete"><i class="glyphicon glyphicon-remove"></i> <? $this->show('Clear all'); ?></button>
        <button class="btn btn-primary" type="submit" onclick="this.form.submit()"><i class="glyphicon glyphicon-search"></i> <? $this->show('Filter'); ?></button>
    </div>

    <div class="table-responsive">
        <?= Grid::render($data, [
            // A column to be considered as a primary key
            'pk' => 'id',
            'batch' => false,
            'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
            'columns' => [
                [
                    'column' => 'id',
                    'label' => 'ID'
                ],

                [
                    'column' => 'hotel',
                    'type' => 'text',
                    'filter' => true,
                    'hidden' => !$shared
                ],

                [
                    'column' => 'datetime',
                    'type' => 'text',
                    'filter' => true,
                    'label' => 'Date and time'
                ],

                [
                    'column' => 'amount',
                    'type' => 'text',
                    'filter' => true,
                    'value' => function($row){
                        return number_format($row['amount']) . PHP_EOL . $row['currency'];
                    }
                ]
            ]

        ], $this->translator, $route, $query); ?>

    </div>

    <? $this->loadPartial('pagination'); ?>
</form>

<? $this->loadPartial('client-modal'); ?>
