<?php

use Krystal\Form\Element;

?>

<script>
    // Statistic
    window.stat = {
        data: <?= json_encode($data); ?>,
        months: <?= json_encode($this->translateArray(array_values($months))); ?>,
        label: {
            totalReservations: "<?php $this->show('Total reservations'); ?>",
            totalIncoming: "<?php $this->show('Total incoming'); ?>",
            totalTax: "<?php $this->show('Total tax'); ?>",
            summary: "<?php $this->show('Summary statistic for year'); ?>"
        }
    };
</script>

<div class="row">
    <div class="col-lg-6">
        <canvas id="canvas"></canvas>
    </div>

    <div class="col-lg-6">
        <form class="form-horizontal" action="<?= $this->url('Site:Stat@reportAction'); ?>">
            <div class="form-group">
              <label class="col-lg-2 control-label"><? $this->show('Price group'); ?></label>
              <div class="col-lg-10">
                <?= Element::select('price_group_id', $priceGroups, null, ['class' => 'form-control']); ?>
              </div>
            </div>

            <div class="form-group">
              <label class="col-lg-2 control-label"><? $this->show('Year'); ?></label>
              <div class="col-lg-10">
                <?= Element::number('year', $year, ['class' => 'form-control']); ?>
              </div>
            </div>

            <div class="form-group">
              <label class="col-lg-2 control-label"><? $this->show('Select months'); ?></label>
              <div class="col-lg-10">
                <?= Element::select('months[]', $this->translateArray($months), '*', ['class' => 'form-control', 'multiple' => true]); ?>
              </div>
            </div>

            <div class="form-group">
              <label class="col-lg-2 control-label"><? $this->show('Select rooms'); ?></label>
              <div class="col-lg-10">
                <?= Element::select('rooms[]', $rooms, '*', ['class' => 'form-control', 'multiple' => true]); ?>
              </div>
            </div>

            <div class="form-group">
              <div class="col-lg-10 col-lg-offset-2">
                <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-stats"></i> <?php $this->show('Generate'); ?></button>
                <a href="#" data-button="back" class="btn btn-info hidden-print"><i class="glyphicon glyphicon-chevron-left"></i> <?php $this->show('Back'); ?></a>
              </div>
            </div>
        </form>
    </div>
    
</div>

