
<?php if (!$isTranslator): ?>
<p>
    <a class="btn btn-primary" href="<?= $this->url('Site:Review:ReviewType@addAction'); ?>"><? $this->show('Add review type'); ?></a>
</p>
<?php endif; ?>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th><?php $this->show('Name'); ?></th>
            <th><?php $this->show('Order'); ?></th>
            <th><?php $this->show('Mark'); ?></th>
            <th><?php $this->show('Actions'); ?></th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($reviewTypes as $reviewType): ?>
        <tr class="<?= $reviewType['id'] == $entity['id'] ? 'success' : null; ?>">
            <td><?= $reviewType['id']; ?></td>
            <td><?= $reviewType['name']; ?></td>
            <td><?= $reviewType['order']; ?></td>
            <td><?= $reviewType['mark']; ?></td>
            <td>
                <a href="<?= $this->url('Site:Review:ReviewType@editAction', $reviewType['id']); ?>"><i class="glyphicon glyphicon-pencil"></i></a>

                <?php if (!$isTranslator): ?>
                <a href="<?= $this->url('Site:Review:ReviewType@deleteAction', $reviewType['id']); ?>"><i class="glyphicon glyphicon-remove"></i></a>
                <?php endif; ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>