<?php

use Krystal\Form\Element;

?>

<form class="form-horizontal" action="<?= $this->url('Site:Architecture:Room@saveAction'); ?>">
  <fieldset>
    <legend><i class="glyphicon glyphicon-pencil"></i> <? $this->show($entity['id'] ? 'Edit the room' : 'Add a room'); ?></legend>

    <?= Element::hidden('id', $entity['id']); ?>

    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Name'); ?></label>
      <div class="col-lg-10">
        <?= Element::text('name', $entity['name'], array('class' => 'form-control', 'placeholder' => $this->translate('Type name or number of the room'))); ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Floor'); ?></label>
      <div class="col-lg-10">
        <?= Element::select('floor_id', $floors, $entity['floor_id'], array('class' => 'form-control')); ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Maximal person amount'); ?></label>
      <div class="col-lg-10">
        <?= Element::number('persons', $entity['persons'], array('class' => 'form-control', 'min' => 1, 'placeholder' => $this->translate('Type maximal amount of people this room can accept'))); ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Room type'); ?></label>
      <div class="col-lg-10">
        <?= Element::select('type_id', $roomTypes, $entity['type_id'], array('class' => 'form-control')); ?>
      </div>
    </div>
    
    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Square'); ?></label>
      <div class="col-lg-10">
        <?= Element::number('square', $entity['square'], array('class' => 'form-control', 'min' => 0, 'step' => '0.01', 'placeholder' => $this->translate('Square of the room'))); ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Room quality status'); ?></label>
      <div class="col-lg-10">
        <?= Element::select('quality', $this->translateArray($roomQualities), $entity['quality'], array('class' => 'form-control')); ?>
      </div>
    </div>
    
    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Cleaning status'); ?></label>
      <div class="col-lg-10">
        <?= Element::select('cleaned', $this->translateArray($cleaningCollection->getAll()), $entity['cleaned'], array('class' => 'form-control')); ?>
      </div>
    </div>
    
    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Description'); ?></label>
      <div class="col-lg-10">
        <?= Element::textarea('description', $entity['description'], array('class' => 'form-control', 'rows' => 7, 'placeholder' => $this->translate('Room description'))); ?>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <a href="<?= $this->url('Site:Architecture:Grid@indexAction'); ?>" class="btn btn-danger"><? $this->show('Back'); ?></a>
        <button type="submit" class="btn btn-primary"><? $this->show('Submit'); ?></button>
      </div>
    </div>
  </fieldset>
</form>
