
<div class="table-responsive">
    <p>
        <a href="<?php echo $this->url('Site:Architecture:Room@addAction'); ?>" class="btn btn-success"><? $this->show('Add a room'); ?></a>
        <a class="btn btn-primary" href="<?= $this->url('Site:Architecture:RoomType@indexAction'); ?>"><i class="glyphicon glyphicon-link"></i> <? $this->show('Room types'); ?></a>
    </p>

    <table class="table table-bordered table-striped table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th><? $this->show('Name'); ?></th>
                <th><? $this->show('Floor'); ?></th>
                <th><? $this->show('Type'); ?></th>
                <th><? $this->show('Square'); ?></th>
                <th><? $this->show('Maximal person amount'); ?></th>
                <th><? $this->show('Cleaning status'); ?></th>
                <th><? $this->show('Room quality status'); ?></th>
                <th><? $this->show('Actions'); ?></th>
            </tr>
        </thead>

        <tbody>
            <?php foreach ($rooms as $index => $room): ?>
            <tr>
                <td><?php echo $index + 1; ?></td>
                <td><?php echo $room['name']; ?></td>
                <td><?php echo $room['floor']; ?></td>
                <td><?php echo $room['type']; ?></td>
                <td><?php echo $room['square']; ?></td>
                <td><?php echo $room['persons']; ?></td>
                <td><?php $this->show($cleaningCollection->findByKey($room['cleaned'])); ?></td>
                <td><?php $this->show($roomQualityCollection->findByKey($room['quality'])); ?></td>
                <td>
                    <a href="<?php echo $this->url('Site:Architecture:RoomInventory@indexAction', $room['id']); ?>"><i class="glyphicon glyphicon-eject"></i></a>
                    <a href="<?php echo $this->url('Site:Architecture:Room@editAction', $room['id']); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                    <a data-button="delete" href="<?php echo $this->url('Site:Architecture:Room@deleteAction', $room['id']); ?>"><i class="glyphicon glyphicon-remove"></i></a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
