<?php

use Krystal\Form\Element;

// Create room ID
$roomId = isset($roomId) ? $roomId : $entity['room_id'];

?>

<form class="form-horizontal" action="<?= $this->url('Site:Architecture:RoomGallery@saveAction'); ?>">
  <fieldset>
    <legend><i class="glyphicon glyphicon-pencil"></i> <? $this->show($entity['id'] ? 'Edit the photo' : 'Add a photo'); ?></legend>

    <?= Element::hidden('id', $entity['id']); ?>
    <?= Element::hidden('room_id', $roomId); ?>

    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Photo'); ?></label>
      <div class="col-lg-10">
        <?= Element::text('photo', $entity['photo'], array('class' => 'form-control')); ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Order'); ?></label>
      <div class="col-lg-10">
        <?= Element::number('order', $entity['order'], array('class' => 'form-control', 'min' => 0)); ?>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <a href="<?= $this->url('Site:Architecture:RoomGallery@indexAction', $roomId); ?>" class="btn btn-danger"><? $this->show('Back'); ?></a>
        <button type="submit" class="btn btn-primary"><? $this->show('Submit'); ?></button>
      </div>
    </div>
  </fieldset>
</form>