<?php

use Krystal\Form\Element;
use Site\Service\LanguageService;

?>

<form action="<?= $this->url('Site:HotelType@saveAction'); ?>">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#type" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Type'); ?></a></li>
        <li role="presentation"><a href="#configuration" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Configuration'); ?></a></li>
	</ul>

    <div class="tab-content">
        <div class="tab-pane fade in active" id="type" role="tabpanel">
            <div class="well">
                <?php $this->loadPartial('language-tabs'); ?>

                <div class="tab-content">
                    <?php foreach ($languages as $index => $language): ?>
                    <div class="tab-pane fade in <?= $index == 0 ? 'active' : null; ?>" id="<?php printf('language-%s', $language['id']); ?>" role="tabpanel">
                        <?php $entity = LanguageService::findByLangId($language['id'], $hotelType); ?>

                        <?= Element::hidden(sprintf('translation[%s][id]', $language['id']), $entity['id']); ?>
                        <?= Element::hidden(sprintf('translation[%s][lang_id]', $language['id']), $language['id']); ?>

                        <?php $this->loadPartial('language-name', ['language' => $language]); ?>

                        <div class="form-group">
                          <label class="col-lg-2 control-label"><? $this->show('Name'); ?></label>
                          <div class="col-lg-10">
                            <?= Element::text(sprintf('translation[%s][name]', $language['id']), $entity['name'], array('class' => 'form-control')); ?>
                          </div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>

        <?php $hotelType = LanguageService::normalizeEntity($hotelType); ?>

        <div class="tab-pane fade in" id="configuration" role="tabpanel">
            <div class="well">
                <?= Element::hidden('type[id]', $hotelType['id']); ?>

                <div class="form-group">
                  <label class="col-lg-2 control-label"><? $this->show('Order'); ?></label>
                  <div class="col-lg-10">
                    <?= Element::text('type[order]', $hotelType['order'], array('class' => 'form-control')); ?>
                  </div>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <br />
        <a href="<?= $this->url('Site:HotelType@indexAction'); ?>" class="btn btn-danger"><? $this->show('Cancel'); ?></a>
        <button type="submit" class="btn btn-primary"><? $this->show('Submit'); ?></button>
      </div>
    </div>
</form>
