<?php

use Krystal\Form\Element;
use Site\Service\LanguageService;

?>

<form action="<?= $this->url('Site:Facility:Category@saveAction'); ?>" class="form-horizontal">
    <?php $this->loadPartial('language-tabs'); ?>

    <div class="tab-content">
        <?php foreach ($languages as $index => $language): ?>
        <div class="tab-pane fade in <?= $index == 0 ? 'active' : null; ?>" id="<?php printf('language-%s', $language['id']); ?>" role="tabpanel">

            <?php $entity = LanguageService::findByLangId($language['id'], $category); ?>

            <?= Element::hidden(sprintf('translation[%s][id]', $language['id']), $entity['id']); ?>
            <?= Element::hidden(sprintf('translation[%s][lang_id]', $language['id']), $language['id']); ?>

            <?php $this->loadPartial('language-name', ['language' => $language]); ?>

            <div class="form-group">
              <label class="col-lg-2 control-label"><? $this->show('Name'); ?></label>
              <div class="col-lg-10">
                <?= Element::text(sprintf('translation[%s][name]', $language['id']), $entity['name'], array('class' => 'form-control')); ?>
              </div>
            </div>
        </div>
        <?php endforeach; ?>

        <?= Element::hidden('category[id]', $entity['id']); ?>

    </div>

    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Order'); ?></label>
      <div class="col-lg-10">
        <?= Element::text('category[order]', $entity['order'], array('class' => 'form-control')); ?>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <br />
        <a href="<?= $this->url('Site:Facility:Grid@indexAction'); ?>" class="btn btn-danger"><? $this->show('Cancel'); ?></a>
        <button type="submit" class="btn btn-primary"><? $this->show('Submit'); ?></button>
      </div>
    </div>
</form>