<?php

use Krystal\Form\Element;

?>

<form class="form-horizontal" action="<?= $this->url('Site:Facility:Category@saveAction'); ?>">
  <fieldset>
    <legend><i class="glyphicon glyphicon-pencil"></i> <? $this->show($category['id'] ? 'Edit the category' : 'Add new category'); ?></legend>

    <?= Element::hidden('id', $category['id']); ?>

    <div class="form-group">
      <label class="col-lg-2 control-label"><? $this->show('Name'); ?></label>
      <div class="col-lg-10">
        <?= Element::text('name', $category['name'], array('class' => 'form-control')); ?>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <a href="<?= $this->url('Site:Facility:Grid@indexAction'); ?>" class="btn btn-danger"><? $this->show('Cancel'); ?></a>
        <button type="submit" class="btn btn-primary"><? $this->show('Submit'); ?></button>
      </div>
    </div>
  </fieldset>
</form>